### ISSUE TITLE
Assigning random security groups by default is not ideal behavior.

### ISSUE THREAD

**Issue by empath-nirvana** [aws/karpenter#1039]
## Version

**Karpenter**: v0.0.0

**Kubernetes**: v1.0.0

## Expected Behavior

I recognize that the documentation points out that if you use the cluster name tag, it will randomly assign security groups, but I can't imagine a single situation where this would be desired behavior.  Either it needs to be deterministic, or it shouldn't provision nodes at all using that selector.   It's especially bad that choosing that tag is the _default_ if you don't specify it!  This is going to break clusters quite frequently if people just don't specify a different tag.

## Actual Behavior

Applying random security groups is fairly unexpected and it makes it extraordinarily difficult to troubleshoot if you aren't expecting it and can have catastrophically bad outcomes for the cluster -- in our case, it was a cluster-wide outage that took out core functionality like coredns.

**Comment by ellistarn** [comment]
Agree that the nondeterministic behavior is a problem. We'd like to address this at the root with the LB controller relaxing their single-sg requirement. In the short term, I think we should probably just alphabetize to ensure deterministic behavior.

**Comment by empath-nirvana** [comment]
Personally, I think I'd prefer that it not be the default setting -- just make it a required field unless you've got a tag that does what one would naturally expect

**Comment by ellistarn** [comment]
I could see potentially including all security groups, and leaving it up to the user to define a security group selector that does not violate the LB controller's assumptions.

**Comment by tobernguyen** [comment]
> I recognize that the documentation points out that if you use the cluster name tag, it will randomly assign security groups

Hi @empath-nirvana Can you point me to the part of document you mentioned? I couldn't find one.


@ellistarn I believe we are experiencing the same problem. We have nginx-ingress controller and I believe the AWS LB Controller created a SG for that the associated ELB with the same tag of the default SG that was created of EKS (with pattern: `kubernetes.io/cluster/CLUSTER_NAME: owned`). And Karpenter just picks this SG for all new created nodes and thus all workloads deployed on the node failed to work since they don't have correct network access.

What can be a workaround in this case (and if we don't want to manually modify AWS resources)?

**Comment by suket22** [comment]
Coming in 0.5.4
