### ISSUE TITLE
Encrypted EBS without using Launch Template

### ISSUE THREAD

**Issue by JohnMops** [aws/karpenter#1086]
**Tell us about your request**
An option to specify EBS encryption as part of the Provisioner CRD

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We currently have a CSP policy to prevent provisioning of non encrypted EBS volumes on all accounts.
When using Provisioner without a launch template , the nodes will not spin up because if that.

**Are you currently working around this issue?**
Using launch template and configuring the encryption solves this issue but I would like an option to eliminate the use of launch template creation all together and configure the nodes via the Provisioner spec only.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
I'm unfamiliar with this. Can you point me towards the specific setting that needs to be set or an example of an LT you're using? I'm looking at blockdevicemappings in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html. 

We don't currently set one, so I'm guessing the default boot volume is unencrypted.

**Comment by JohnMops** [comment]
Hey, 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html

By default the first api call to create an instance is unencrypted and then the policy gets evaluated.
It’s not a deal breaker but would be great if we can eliminate the need for templates altogether

**Comment by ellistarn** [comment]
Adding this to our upcoming work on launch-templates. @suket22 is owning this.

**Comment by bwagner5** [comment]
https://github.com/aws/karpenter/pull/1235

**Comment by djtje12** [comment]
Don't know if this is the correct place or if I need to create a new issue, so please let me know.

This EBS disk encryption doesn't work correctly for Bottlerocket, [Bottlerocket has 2 disks /dev/xvda & dev/xvdb](https://github.com/bottlerocket-os/bottlerocket/issues/1203). The first disk is now encrypted by this merge but the dev/xvdb is not.

See screenshot below how the launchtemplate now looks like encryption wise. For us this is an issue since our AWS team enforces that both disks are encrypted.
![Screenshot 2022-02-23 at 20 39 46](https://user-images.githubusercontent.com/46244867/155395345-b52171de-0fe2-4023-a398-dd41ceeb4408.png)

**Comment by bwagner5** [comment]
Can you open a new issue with this info? Just want to make sure this is being tracked effectively :)
