### ISSUE TITLE
provider api docs are not up to date

### ISSUE THREAD

**Issue by matti** [aws/karpenter#1102]
**Tell us about your request**
The tutorial at https://karpenter.sh/docs/getting-started/ references "limits:" field that is not listed in https://karpenter.sh/docs/provisioner/, but I could find that some design specs are at https://github.com/aws/karpenter/blob/main/designs/limits.md

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It is kinda hard to get started when.

**Are you currently working around this issue?**
Banging my head around the walls

**Additional context**
I think I'll go back to non-karpenter world, this doesn't feel production ready at all.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Hey @matti,
The project is evolving quickly, and we're adding new features all the time. Because of this, the docs are lagging a bit, and it really sucks you had a confusing experience. 

I imagine that this sense isn't just lack of documentation, but a combination of issues adding up to a sense of things not being quite where they should be. If you're willing to take the time, I'd love to hear a list of things that don't feel right so we can try to course correct and deliver a better getting started experience for new users.

**Comment by johngmyers** [comment]
The Provisioner API documentation https://karpenter.sh/v0.5.5/provisioner/ omits any documentation of the "limits" field.

The fields `ttlSecondsUntilExpired`, `ttlSecondsAfeterEmpty`, `taints`,  and `labels` are only documented in the example, not in the body of the document. The field `kubeleteConfiguration` is only documented in the body, not in the example.

**Comment by johngmyers** [comment]
It would probably be clearer to put the page documenting the AWS-specific provisioner API as a sub-page of "Provisioner API" instead of as a sub-page of "AWS".

**Comment by suket22** [comment]
Hey @johngmyers, We've updated the docs now so you can see documentation about limits here - 
https://karpenter.sh/v0.6.0/provisioner/#speclimits

> The fields ttlSecondsUntilExpired, ttlSecondsAfeterEmpty, taints, and labels are only documented in the example, not in the body of the document. The field kubeleteConfiguration is only documented in the body, not in the example.

Good callout, we should definitely fix this. @geoffcline could we get the provisioner doc updated so that atleast everything in the example is reflected in the body?

**Comment by geoffcline** [comment]
I opened #1419 to address this. 

I decided not to add further description of taints/labels as the existing content seemed sufficient.

**Comment by bwagner5** [comment]
Document:
```
spec:
  ttlSecondsUntilExpired
  ttlSecondsAfterEmpty
  taints
  labels
```
