### ISSUE TITLE
Question: How to limit the max size of a cluster?

### ISSUE THREAD

**Issue by StarpTech** [aws/karpenter#1104]
Hi, how can I ensure the maximum number of nodes? Will `karpenter` respect the configuration of a managed eks cluster (eskctl `maxSize`)?

**Comment by adefrasne** [comment]
Hi,
You cannot specify yet a max number of nodes, but a workaround may to fine-tune your instance types and assign a hard resources limit as shown in the example config : https://karpenter.sh/docs/getting-started/#provisioner

**Comment by ellistarn** [comment]
You can specify max resources `spec.limits.resources`. We need to document this. Closing as dup of https://github.com/aws/karpenter/issues/1003.

**Comment by olemarkus** [comment]
Just a thought here. Just like you have maxPods in addition to cpu/mem, it does make sense to have max nodes. From control plane perspective, each node does have some overhead. That's why it is quite common for e.g CNIs to specify scaling thresholds both in terms of number of pods in the cluster and number of nodes.

Granted, some of this should be mitigated by disallowing nodes that are too small, it is still not that unreasonable. Somewhat related to the defrag problem in #1091, karpenter could consider growing the instance sizes when the "maxNodes" limit is approaching.

**Comment by StarpTech** [comment]
@adefrasne @ellistarn thanks, this is what I'm looking for. I want to avoid that an infinite number of nodes are provisioned. We use karpenter to deploy preview environments.
