### ISSUE TITLE
Handling of 'Spot Instance interruptions'

### ISSUE THREAD

**Issue by Miszcz-AndY** [aws/karpenter#1184]
**What karpenter features are relevant?**
spot Instance interruption

**How should the docs be improved?**
If it's true that karpenter is taking care of ec2 notifications (including Spot Instance interruptions) will be super to read about it in the official documentation. I'm not sure if there is such feature but because of [this info](https://www.youtube.com/watch?v=43g8uPohTgc&t=1251s) I decided to ask.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by prateekgogia** [comment]
Hi @Miszcz-AndY 

At the moment Karpenter doesn't handle ec2 notifications, the way it works today is - If a node is terminated in EC2, Kubernetes will try to reschedule the pods to a different node if there is capacity. Otherwise, these pods will go pending and Karpenter will see these pending pods and launch the required capacity in EC2.

The youtube link you have provided is more of a set of features we plan to add to Karpenter to help scale and manage nodes in the cluster.

Also, we have a [Karpenter slack](https://kubernetes.slack.com/archives/C02SFFZSA2K) channel for discussions, feel free to join, ask more questions/provide feedback.

**Comment by ellistarn** [comment]
FYI, this is a duplicate of https://github.com/aws/karpenter/issues?q=is%3Aissue+is%3Aopen+termination

**Comment by jhecking** [comment]
In this [Using Amazon EC2 Spot Instances with Karpenter](https://aws.amazon.com/blogs/containers/using-amazon-ec2-spot-instances-with-karpenter/) blog post it is mentioned that "Karpenter does not handle Spot Instance interruption natively, although **this feature is in the roadmap**." (Emphasis mine.) Is this roadmap public somewhere? If so, I couldn't find it.
