### ISSUE TITLE
Karpenter fails to create node object if an instance does not have PrivateDnsName still an issue

### ISSUE THREAD

**Issue by bwmetcalf** [aws/karpenter#1282]
## Version
**Karpenter**: v0.5.4

**Kubernetes**: v1.21.5

## Actual Behavior
We have seen this issue twice in the past week running 0.5.4.  According to #1067, the issue is fixed in 0.5.4.

```2022-02-07T15:40:39.115Z        ERROR   controller.provisioning Could not launch node, launching instances, All attempts fail:
#1: got instance i-0eaa445d1c9aa01bb but PrivateDnsName was not set
#2: got instance i-0eaa445d1c9aa01bb but PrivateDnsName was not set
#3: got instance i-0eaa445d1c9aa01bb but PrivateDnsName was not set     {"commit": "7e79a67", "provisioner": "gitlab-runner-provisioner-karpenter-provisioner"}
```

## Resource Specs and Logs
Same issue as #1067

**Comment by ellistarn** [comment]
To be clear from that issue, this is an unfortunate race condition that EC2 sometimes takes a long time to propagate the private dns name. If you're using karpenter owned launch templates, it should still register and work since karpenter injects all the expected labels into the userdata. If you're using a custom launch template, make sure you include `karpenter.sh/provisioner-name` as a label passed to the kubelet. 

I think we could explore increasing the retries/timeout on EC2, as well.

**Comment by ellistarn** [comment]
To be clear from that issue, this is an unfortunate race condition that EC2 sometimes takes a long time to propagate the private dns name. If you're using karpenter owned launch templates, it should still register and work since karpenter injects all the expected labels into the userdata. If you're using a custom launch template, make sure you include `karpenter.sh/provisioner-name` as a label passed to the kubelet. 

I think we could explore increasing the retries/timeout on EC2, as well.

**Comment by felix-zhe-huang** [comment]
Is there a known way to reproduce this bug constantly?
