### ISSUE TITLE
Support for density optimized memory overhead 

### ISSUE THREAD

**Issue by yerenkow** [aws/karpenter#1295]
There are use case for using nodes for one (or just a few) of large, CPU & Memory intensive jobs.
To make it most effective, whole node memory should be allocated to the pod.
This can be achieved by tuning maxPods and kubeReserved.memory to lower values (like ~20 and ~1GB).
Then almost all memory can be allocated to a particular pod.

The mentioned change is possible via providing user data script in launch template, so launched node will be registered in the k8s with more memory than with usual karpenter provisioner.

Unfortunately, it's not possible to schedule large pod with karpenter, as there is no way to change hard-coded 92,5% of allocatable memory:
https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/instancetype.go#L32

Also, this ratio is highly ineffective in case of high-end instance types with huge amount of memory.

As of now,  I don't see other way than patching the karpenter to change the ratio. Not sure if that's feasible and maintainable in the long run. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
There's been some discussion of this: https://github.com/aws/karpenter/issues/445

There's a fundamental parameter needed to control how much resources should be reserved by the kubelet. As you say, for single pod scenarios, you want this value to be very small. For higher densities, you want this value to be much larger. 

There are some complicating factors:

1. Static values don't work well across instance types, but Karpenter provisioners are designed to support multiple
2. Existing CNI implementations (vpc-cni < v1.9) affect max pods
3. High densities can impact performance due to cpu thrashing
4. High densities can result in large percentages of the node being reserved 
5. Nodes do not have uniform densities over their lifetime (e.g., pods can terminate or be scheduled over time)
6. Once configured for 100 pods worth of overhead, a node must be restarted/reconfigured to free the resources if there only ends up being a single pod.
7. Memory overhead is nonuniform for different CRI providers (docker, containerd, etc)
8. I want to avoid bloating the provisioner spec such that it's only useful for power users

Ideally we should have some dynamic solution (e.g. pods-per-gb) that works for many instance type and allows the user to specify a single value at the provisioner level that expresses their requirements. Problem 2 shouldn't impact the long term story, since solutions like prefix delegation make this problem disappear. I'd like to ignore problem 3 as well, but it's something to consider for high densities (upstream caps out at 110). For problem 7, I'd love to just assume containerd, as it appears this is the way the wind is blowing.

**Comment by bwagner5** [comment]
Does the global setting of `aws.vmMemoryOverheadPercent` support what you want to do? https://karpenter.sh/preview/concepts/settings/#:~:text=aws.vmMemoryOverheadPercent%3A%20%220.075%22

**Comment by bwagner5** [comment]
Feel free to reopen if this is still an issue!
