### ISSUE TITLE
Skip provisioner.spec.securityGroupSelector if provided in custom launch template

### ISSUE THREAD

**Issue by bwmetcalf** [aws/karpenter#1303]
## Version
**Karpenter**: v0.6.1
**Kubernetes**: v1.21.5

## Expected Behavior
`securityGroupSelector` should not be required.  We have the security groups built into our launch template.

## Actual Behavior
We upgraded from 0.5.4 to 0.6.1 and now get the following when installing our provisioners:
```
│ Error: admission webhook "validation.webhook.provisioners.karpenter.sh" denied the request: validation failed: missing field(s): spec.provider.securityGroupSelector
```
We do not get this error with 0.5.4.

## Steps to Reproduce the Problem
Install karpenter 0.6.1 and then install a provisioner that doesn't specify `securityGroupSelector`

**Comment by felix-zhe-huang** [comment]
Hi Brandon, starting from v0.5.5, we remove auto discovery of security group via cluster name to avoid tag limitations for multi-cluster discovery. In this case, Karpenter relies on the users to defined how to tag their own security group for different use cases. Therefore, the tag must be provided as part of the provisioner definition. 

Karpenter is also launch template agnostic in order to maintain a strict separation of concerns between itself and cloudprovider. Therefore Karpenter will not be able to extract the security group tag value from the launch template.

**Comment by felix-zhe-huang** [comment]
Before v0.5.5, karpenter used the hardcoded tag value `kubernetes.io/cluster/$CLUSTER_NAME` if no security group selector tag is provided in the provisioner definition. In the getting started guide, [there is a step ](https://karpenter.sh/v0.4.3/getting-started/#tag-subnets)that created this hardcoded tags for the subnet and security group. You may have carried out this step as part of setting up your cluster. I believe that's why no securityGroupSelector is needed in the provisioner.

**Comment by woz5999** [comment]
If a launch template is supplied that includes security groups, does Karpenter ignore the launch template security groups?

**Comment by felix-zhe-huang** [comment]
> does Karpenter ignore the launch template security groups?

No, if the launch template is provided its security group will be used directly.

> t seems redundant and unnecessary to require security group selectors to also be supplied
That's a good point. the karpenter AWS provider can check if the security group is specified in the launch template. If so, it will not require specifying securityGroupSelector in the provisioner.

**Comment by felix-zhe-huang** [comment]
> Karpenter is also launch template agnostic in order to maintain a strict separation of concerns between itself and cloudprovider. Therefore Karpenter will not be able to extract the security group tag value from the launch template.

BTW, I was wrong saying the above. The cloud provider in Karpenter can implements these logics and still maintain the separation of concerns. At this point if the user provides a custom launch template, they are also responsible to maintain it. We need to be careful when introducing the extra complexity into the provider implementations. We don't want to blur the boundary by too much.

**Comment by woz5999** [comment]
I agree there's some push and pull. How much does karpenter really want to have to know about the internals of the launch template for field validation? On the other hand, as a user, when you've already accepted the burden of managing the complexity of the launch templates, it's annoying to have to also specify fields that aren't at all applicable to your use case.

**Comment by felix-zhe-huang** [comment]
> it's annoying to have to also specify fields that aren't at all applicable to your use case.

I agree with this. I think we can change it so that if a custom launch template is provided, we no longer requires those fields in the provisioner validation since they are redundant. 

> How much does karpenter really want to have to know about the internals of the launch template for field validation?
If I understand correctly, Karpenter does not validate the launch template. It will be up to the user to make sure that the launch template will work for their use cases.

**Comment by suket22** [comment]
I think we should always skip validating that `securityGroupSelector` is specified if a launch template was provided, irrespective of what the contents of the launch template are. 

Our current semantic is that if you give us a launch template, everything must be contained within it, including security groups. So the existence of the launch template in the providerSpec is enough signal.

**Comment by bwagner5** [comment]
https://github.com/aws/karpenter/pull/1323 adds new validation that will reject parameters that will be overridden by the custom LT.  The current parameters that will be rejected with a custom LT when v0.6.2 is released are: `securityGroupSelector`, `instanceProfile`, `amiFamily`, and `metadataOptions`.
