### ISSUE TITLE
Failed to bind ... Operation cannot be fulfilled ... pod ... is already assigned to node ...

### ISSUE THREAD

**Issue by ottokruse** [aws/karpenter#1537]
## Version

**Karpenter**: v0.6.3

**Kubernetes**: v1.21.5-eks-bc4871b

## Expected Behavior
No errors are thrown by Karpneter when scaling.

## Actual Behavior
Karpenter throws errors when scaling.

Note, in the end the scaling works, so the errors are not blocking, but it seems Karpenter sometimes steps on it's own toes:

`ERROR	controller.provisioning	Failed to bind default/1647597043900-543-87rbh to ip-192-168-165-50.eu-west-1.compute.internal, Operation cannot be fulfilled on pods/binding "1647597043900-543-87rbh": pod 1647597043900-543-87rbh is already assigned to node "ip-192-168-63-207.eu-west-1.compute.internal"	{"commit": "fd19ba2", "provisioner": "default"}`

The node that is being reported, `ip-192-168-63-207.eu-west-1.compute.internal`, is also a node that is managed by Karpenter.

## Steps to Reproduce the Problem
Launch a lot of jobs (e.g. 1000)

## Resource Specs and Logs
There is a whole bunch of messages like the one above.

**Comment by njtran** [comment]
Hey @ottokruse! Thanks for opening this. This is a natural part of Kubernetes scaling up. 

When Karpenter provisions capacity in response to pending pods, we bind pods to those nodes before the nodes become ready to ensure pods schedule as desired. If capacity becomes available while Karpenter is scaling, the Kubernetes scheduler will schedule existing pods to those nodes if they fit the scheduling constraints. When Karpenter then calls to bind the pods to the nodes it has provisioned, it will fail and log the error message you mentioned. Since these are valid scheduling decisions, it shouldn't impact the functionality, but could result in slightly loosely bin-packed nodes. 

If you see this happen a lot and it results in very low resource utilization on those nodes, you can use [TTLSecondsUntilExpired](https://github.com/aws/karpenter/blob/main/pkg/apis/provisioning/v1alpha5/provisioner.go#L36-L43) to recycle nodes and have Karpenter do bin-packing again. Look to [here](https://github.com/aws/karpenter/issues/1091) for more information about defragmentation if you're curious. 

Since this is expected, I'm going to tag it so we include it into our documentation.

**Comment by suket22** [comment]
@njtran should we change the log level for this error to WARN? It's not rare for the `kube-scheduler` to beat Karpenter at binding pending pods to a node, and this isn't necessarily an error in karpenter, right?

I suppose this happens more often when there's a ton of pod churn - since a pod can go from unschedulable -> schedulable very quick as there's constantly changing allocatable capacity across nodes etc.

**Comment by ellistarn** [comment]
> @njtran should we change the log level for this error to WARN?

Karpenter philosophically doesn't use WARN. We'd want to log at ERROR or DEBUG instead. The idea being that WARN is unclear about whether or not the message is okay. Explicitly, we're making it clear that this case is OK. I'd probably log at debug to keep the logs clean.

**Comment by chrisnegus** [comment]
@njtran @suket22 @ellistarn Should we describe this behavior in the troubleshooting guide? My thought is that it would be the natural place to look if someone thought this was an error.

**Comment by tzneal** [comment]
This shouldn't happen once #1856 is merged in, which will hopefully occur today.

**Comment by tzneal** [comment]
You shouldn't see this error any longer as we no longer pre-bind pods to nodes.
