### ISSUE TITLE
Discussion - Getting Started Guides

### ISSUE THREAD

**Issue by bryantbiggs** [aws/karpenter#1574]
**Is an existing page relevant?**
- https://github.com/aws/karpenter/pull/1332

**What karpenter features are relevant?**
Getting started guides and minimum requirements for provisioning Karpenter

**How should the docs be improved?**
The getting started guides are great, but I think things are drifting too far into the EKS realm and tools that provision EKS clusters as opposed to staying Karpenter centric. 

eksctl and kops are cluster provisioning tools whereas Terraform and CloudFormation are infrastructure as code tools that eksctl, kops, etc. are built on top of. None of them have anything to do with Karpenter.

I think the maintenance and overhead for this project would be reduced if it were to not focus on "How to bootstrap a cluster AND THEN run Karpenter" and instead focus on "How to provision Karpenter" or more succinctly "What is required to provision Karpenter"

In my brief experience with Karpenter there are a few core components that are required and they can be readily provided in various forms (frameworks, DSLs, etc.):
1. EKS cluster with OIDC identity provider enabled
2. Subnets for Karpenter to utilize (discovery tag can be applied or subnets can be specified in the provisioner)
3. Security group for Karpenter to utilize (again, discovery tag can be applied or security group can be specified in the provisioner)
3. IAM role that allows for `AssumeRoleWithWebIdentity` (for IRSA) in trust policy
4. IAM role policy for Karpenter (related #507 and #1332 ) 
*5. Tags that tie scoped role policy to provisioner created resources. I denote with an `*` because I think since the provisioner is taking in the cluster name/id, it would be worthwhile for Karpenter to automatically create a tag which is stable for things like the IAM policy scoping rather than relying on users to ensure that they added that to the provisioner. TBD

This aligns with other community projects where an IAM policy along with some supporting details are provided in a README and the methods for provisioning are left up to users. The 5 points above would fit into one, short and to the point page which gives users a clear picture of what they need to run Karpenter. This should drastically cut down on the number of updates for drift as those supporting tools change over time. In lieu of this, one optional section would be a reference section. If the eksctl project wants to host a "How to provision Karpenter" guide then adding a link for users would be great - and it keeps that burden off this project and in the hands of the eksctl team. Whether this goes forward or not, I am planning to this for the terraform-aws-eks module anways, for a number of different reasons (https://github.com/clowdhaus/eks-reference-architecture)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aquarhead** [comment]
Thank you so much for this list! I'm definitely on the same page that infra softwares should provide detailed install requirements instead of (or not only) "one click" solutions with helm.

Also for example the list item 2 and 3 depends on how the IAM policy is setup, it took me a while to make the connection.

**Comment by bbhenry** [comment]
I agree, I was confused by the inconsistent description for about tagging subnets and security groups across different provisioning pages. I just know something was not making sense and it let me here. It would've been nice to know I can use selector instead of discorvery tags right from the beginning, and a link to describe why Karpenter needs to know about these things.

**Comment by PeterSzegedi** [comment]
I highly agree with all the points and with @bbhenry. It was very confusing to get started. Also the terraform part of the getting started guide contains an IAM role that will not work without errors, due to not having permissions to access the pricing on AWS.  The guide should be updated a bit, focusing on the karpenter concepts/requirements instead of the whole cluster creation.

**Comment by chrisnegus** [comment]
We have updated the Karpenter getting started experience by simplifying the existing[ Getting Started with Karpenter](https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/) guide (eksctl) and dropping the Terraform and kOps guides. We now point to the EKS Blueprints for Terraform [Getting Started](https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.18.0/getting-started/) guide and kOps [Karpenter ](https://kops.sigs.k8s.io/operations/karpenter/)installation guide for those instructions. See [PR #3312](https://github.com/aws/karpenter/pull/3312) for details.
