### ISSUE TITLE
Helm chart does not work when release name is not "karpenter"

### ISSUE THREAD

**Issue by tidunguyen** [aws/karpenter#1595]
## Version

**Karpenter**: v0.7.3

**Kubernetes**: v1.21.5

## Expected Behavior

Helm chart work with a different release name from the default "karpenter" name in the tutorial (getting started with karpenter on aws)

## Actual Behavior

Helm chart does not work (CrashLoopBackOff from karpenter pod).

## Steps to Reproduce the Problem

1. Follow exactly every step in the Getting started with karpenter on AWS tutorial.
2. Use a different release name when installing the karpenter helm chart.

## Resource Specs and Logs

Log from the karpenter pod:
```
2022-03-30T06:49:17.104Z        INFO    Successfully created the logger.
2022-03-30T06:49:17.104Z        INFO    Logging level set to: debug
2022-03-30T06:49:17.212Z        DEBUG   controller.aws  Using AWS region ap-southeast-1 {"commit": "78d3031"}
2022-03-30T06:49:17.212Z        DEBUG   controller.aws  Discovered caBundle, length 1066        {"commit": "78d3031"}
2022-03-30T06:49:17.212Z        DEBUG   controller.aws.launchtemplate   Hydrating the launch template cache with names matching "Karpenter-tidu-cluster-*"      {"commit": "78d3031"}
{"level":"info","ts":1648622957.2122052,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
panic: Unable to hydrate the AWS launch template cache, WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
        status code: 403, request id: c1775479-9d26-4dd2-9195-f2175ae65099

goroutine 1 [running]:
github.com/aws/karpenter/pkg/cloudprovider/aws.(*LaunchTemplateProvider).hydrateCache(0xc000325db0, {0x27df4f8, 0xc000735b00})
        github.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:231 +0x4f4
github.com/aws/karpenter/pkg/cloudprovider/aws.NewLaunchTemplateProvider({0x27df4f8, 0xc000735b00}, {0x28b3f98, 0xc000126a50}, 0xc000163a20, 0xc000126aa8, 0xc00000d410, 0xc0006381f0)
        github.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:70 +0x225
github.com/aws/karpenter/pkg/cloudprovider/aws.NewCloudProvider({0x27df4f8, 0xc000735ad0}, {0x1fba360})
        github.com/aws/karpenter/pkg/cloudprovider/aws/cloudprovider.go:91 +0x5d3
github.com/aws/karpenter/pkg/cloudprovider/registry.newCloudProvider(...)
        github.com/aws/karpenter/pkg/cloudprovider/registry/aws.go:27
github.com/aws/karpenter/pkg/cloudprovider/registry.NewCloudProvider({0x27df4f8, 0xc000735ad0}, {0x1fba360})
        github.com/aws/karpenter/pkg/cloudprovider/registry/register.go:25 +0x28
main.main()
        github.com/aws/karpenter/cmd/controller/main.go:77 +0x257
```

**Comment by suket22** [comment]
That looks like an issue with the permissions of the Karpenter pod. If you used [the eksctl guide](https://karpenter.sh/v0.8.0/getting-started/getting-started-with-eksctl/#create-the-karpentercontroller-iam-role) to create the KarpenterController role, then you'd also need to edit the trust policy of the IAM role that eksctl has created for you. 

That IAM role should have a trust policy with something like - 
```
"Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-2.amazonaws.com/id/$yourOIDCID:aud": "sts.amazonaws.com",
                    "oidc.eks.us-west-2.amazonaws.com/id/$yourOIDCID:aud:sub": "system:serviceaccount:karpenter:karpenter"
                }
            }
```

When doing an install with a custom releaseName, the serviceAccount should be created with the custom releaseName [because of this I believe](https://github.com/aws/karpenter/blob/7e95b62df90c072bfc295e7aeec4f37dc93647f4/charts/karpenter/templates/_helpers.tpl#L61) so you'd need to fix the trust policy in the IAM role. I was able to replicate the issue using a custom release name too. 


In general I'd say that if you modify something in the Getting started guides, you can end up in situations where things don't work together due to an unintended misconfiguration.

**Comment by suket22** [comment]
Please re-open if that doesn't fix it for you, or if you're running into something else.
