### ISSUE TITLE
Multiple Provisioners

### ISSUE THREAD

**Issue by dotanalter** [aws/karpenter#1758]
## Version
**Karpenter**: v0.9.1
**Kubernetes**: any version

## Expected Behavior
From the docs FAQ page we have the following statement:
"By default, pods will use the rules defined by a provisioner named default. This is analogous to the default scheduler. To select an alternative provisioner, use the node selector karpenter.sh/provisioner-name: alternative-provisioner. You must either define a default provisioner or explicitly specify karpenter.sh/provisioner-name node selector"

This one was valid until v0.9.1, I had 4 provisioners (default - small spots only, spots large, on-demand, on-demand large), and only the default provisioner one was karpenter's option unless I pass the node selector for a different provisioner.

## Actual Behavior
Since v0.9.1 (https://github.com/aws/karpenter/pull/1673) this logic is not valid anymore. I get instances from all of my provisioners and I don't pass the specific node selector. In addition, spots are not preferred as they were before (I get a lot of on-demand instances although spot capacity available)
If it's a new scheduling logic and not a bug please update the docs and help us understand how to achieve the same thing I had before.

## Steps to Reproduce the Problem
create multiple provisioners.

**Comment by tzneal** [comment]
Sorry, that appears to be an error in the docs.  I'm not sure if Karpenter has ever had that behavior.  If multiple provisioners match, it used to pick the first one sorted alphabetically.

From the best practices guide, we recommend [mutually exclusive provisioners](https://aws.github.io/aws-eks-best-practices/karpenter/#create-provisioners-that-are-mutually-exclusive).  

Karpenter currently schedules across provisioners so there isn't an ordering guaranteed if multiple provisioners can potentially schedule a pod.  To make your provisioners mutually exclusive, you could add a different taint to your three "non-default" provisioners and instead of adding a label selector, add a toleration to your workloads.

**Comment by dotanalter** [comment]
Thanks for the explanation. Closing this one.
