### ISSUE TITLE
[Karpenter] [Docs] : Node terminates before ready on failed encrypted EBS volume 

### ISSUE THREAD

**Issue by gowthasa** [aws/karpenter#1926]
**Is an existing page relevant?**
Yes
https://karpenter.sh/v0.10.1/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume 

**What karpenter features are relevant?**
Node terminates before ready on failed encrypted EBS volume. The Karpenter docs in the Troubleshooting page has the below details.
```
If you are using a custom launch template and an encrypted EBS volume, the IAM principal launching the node may not have sufficient permissions to use the KMS customer managed key (CMK) for the EC2 EBS root volume. This issue also applies to [Block Device Mappings](https://karpenter.sh/v0.10.1/aws/provisioning/#block-device-mappings) specified in the Provisioner. In either case, this results in the node terminating almost immediately upon creation.

Keep in mind that it is possible that EBS Encryption can be enabled without your knowledge. EBS encryption could have been enabled by an account administrator or by default on a per region basis. See [Encryption by default](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default) for details.

To correct the problem if it occurs, you can use the approach that AWS EBS uses, which avoids adding particular roles to the KMS policy. 
```

**How should the docs be improved?**
However, in my lab I was using EKS Optimized AMI, Launch templates created by Karpenter and EBS encryption enabled. But, still faced the issue similar to https://github.com/aws/karpenter/issues/1760 and Nodes were getting Terminated before it was ready. 

I went about adding the Karpenter Controller role (IRSA role) as KMS Key users in the KMS console and that solved the issue for me and it was similar to the KMS policy explained here https://karpenter.sh/v0.10.1/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume 

If we can update the documentation with below details : 
- The issue is not specific to custom launch templates, instead can be seen with EKS Optimized AMIs and LTs created by Karpenter
- Also, a note on the docs here https://karpenter.sh/v0.10.1/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume which tells customers that they should add the Karpenter Controller role (IRSA role) and not the Karpenter Node role. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suket22** [comment]
Ah, is the confusion primarily over this bit - `the IAM principal launching the node may not have sufficient permissions to use the KMS customer managed key (CMK)`?

I think the reason it's phrased this way is because we want to avoid making assumption on how someone's set up Karpenter. If you've set up IRSA, then you'd need to update the Karpenter Controller role that's associated with the Karpenter pod. 

If you weren't using IRSA at all and Karpenter is running on your managed worker node, then the nodeRole associated with your managed node group would need to have these permissions. I haven't used EKS on Fargate a bunch, but without IRSA I think it's the pod execution role you'd have to update there. 

I'll try and add a statement to help clarify that. Thanks for opening this.
