### ISSUE TITLE
FAQ ALB ip vs instance mode rationale incorrect?

### ISSUE THREAD

**Issue by anguslees** [aws/karpenter#2171]
> ### How do I use Karpenter with the AWS load balancer controller?
> Set the [ALB target type](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/annotations/#target-type) to IP mode for the pods. Use IP targeting if you want the pods to receive equal weight. Instance balancing could greatly skew the traffic being sent to a node without also managing host spread of the workload.

This sounds incorrect?  I think instance-mode will send traffic equally to all nodes (to a NodePort), and thence equally to all pods (that are ready and match the service selector).

Maybe this section is confusing instance-mode with [`internalTrafficPolicy=Local`](https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/) ?

**Comment by ellistarn** [comment]
Hey Gus! Feel free to cut a PR. I can check in with @chrisnegus on where this information came from.

**Comment by jicowan** [comment]
@anguslees it probably depends on how pods are distributed across the nodes in the cluster. If you don't have a pod anti-affinity policy or are not using topology spread constraints, multiple pods in a Deployment can wind up running on a small number of instances. IP targets are generally recommended because it avoids routing traffic through kube-proxy (> overhead). Unless you're using IPVS, kube-proxy will always default to RR for routing traffic so, assuming an even distribution of pods and a traffic policy of `cluster`, each pod should have equal weight when the target type is instance.

**Comment by ellistarn** [comment]
> routing traffic through kube-proxy (> overhead)
Curious if we have benchmarks on this. IPTables should be pretty fast at most scales.

**Comment by jicowan** [comment]
Using IP targets can preserve the source IP in the HTTP header, making it easier to trace back to the source of the traffic. While I think the recommendation is sound (use IP targets) the rationale might need to be updated.

**Comment by anguslees** [comment]
And just to be clear, I'm saying instance mode will send an equal number of queries to pods _even when those pods are packed unevenly onto nodes_.

(Because the pod-level assignment is actually done by kube-proxy and iptables RR as you described)

**Comment by chrisnegus** [comment]
We decided that this type of content is best suited for the AWS load balancer documentation. So I removed the content from the Karpenter FAQ (see [PR #2245](https://github.com/aws/karpenter/pull/2245)). I then opened an issue for the ALB docs (see [Issue 2747](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2747)).
