### ISSUE TITLE
Docs: Upgrade Guide

### ISSUE THREAD

**Issue by dougbyrne** [aws/karpenter#2323]
Hi, the upgrade guide has example code to replace the CRDs, but the code has spaces in the middle of the URL that break the command when copy and pasting.

https://github.com/aws/karpenter/blob/943de318ca2edfb242a193b3b1bc9eaeb8cd194b/website/content/en/preview/upgrade-guide/_index.md?plain=1#L42-L46

It looks like this URL is built dynamically.

**Comment by njtran** [comment]
Hi @dougbyrne, you're right. We plug this into our release process and automate it so that you can copy paste these commands from the website itself. You're looking at the preview docs which point to HEAD. [Here's the URL](https://karpenter.sh/preview/upgrade-guide/) you want. Let us know if you have any docs improvements you'd want to see! Going to close this otherwise. Feel free to open.

**Comment by dougbyrne** [comment]
Hi, I understand that the rendered docs are available there, the issue is that the renderer has a bug which makes them not usable. In the link you shared, `{{< githubRelRef >}}` is rendered as `main/ ` instead of just `main/`.

**Comment by njtran** [comment]
Ah I see, looking briefly through the repo, that's the only instance I see that has `{{< githubRelRef >}}` outside of a hyperlink markdown format. Re-opening and putting this as a bug as that's definitely not intended.
