### ISSUE TITLE
make consolidation wait a bit

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#2370]
i’ve noticed that consolidation  is a tad toooo quick removing nodes.
sometimes a pod is being replaced, and before the new one even get the change of being scheduled, karpenter kills the node just for 1 or 2 seconds later spinning a new one… this makes the deployment take 1 min for the node to be ready

## Expected Behavior
for karpenter to keep nodes a bit longer so workloads being replaced still have where to go

## Actual Behavior
nodes get ripped too quick

**Comment by ishworg** [comment]
Couldn't agree more.

We have CI runners that launch ephemeral containers and what we saw with `consolidation.enabled` set to true is the OP's precise behaviour. We have now upgraded Karpenter to `v0.16.2` and set old behaviour of `ttlSecondsAfterEmpty` but the node count remains at peak (because pods were scheduled when ephemeral CI runners were launched).

If we could consolidate nodes but at the same time control the pace of consolidation process (node deletion with a TTL perhaps) then that could potentially solve this problem for us.
