### ISSUE TITLE
Allow usage of --force flag for Karpenter drain

### ISSUE THREAD

**Issue by nonoswz** [aws/karpenter#2391]
## Version

**Karpenter**: v0.14.0

**Kubernetes**: v1.21

## Expected Behavior

When a node is drained (e.g.: a node reached its time to leave), I would expect all pods to be drained. I would like to use the `--force` flag (if necessary) to ensure I can drain pods which are missing `ownerReference`.  So we can easily use the TTL feature and do not have stuck nodes. 

## Actual Behavior

Since the [PR](https://github.com/aws/karpenter/issues/2088) to align the drain mechanism to `kubectl drain`, pods without `ownerReference` are not drained and there is no mechanism to allow this as we cannot specify the `--force` flag. `--force` seems to be the way to do as described [here](https://github.com/kubernetes/kubernetes/issues/96382). We would expect that to align with the `kubectl drain` behavior, the `--force` flag should have been added as well. 

We sometimes end up with pods without `ownerReference`, they are usually pods used to debug connectivity. Those pods should be short lived but they are not always deleted from our clusters. Those pods are now blocking the nodes to expire (using `ttlSecondsUntilExpired`), so some nodes are blocked in a `Ready, SchedulingDisabled` state until we `kubectl delete --force` those pods manually. 

We would like a way to configure the drain to use `--force` flag to ensure we can delete those pods during the node expiration. 

## Steps to Reproduce the Problem

1. Deploy a pod without any ownerReference
2. Configure your provisioner to expire the nodes 
3. The node with this specific pod will be stuck in `Ready, SchedulingDisabled`

## Resource Specs and Logs

Provisioner Spec
````
spec:
  kubeletConfiguration: {}
  labels:
    containerd: enabled
    group: default
  limits: {}
  provider:
    amiFamily: AL2
    apiVersion: extensions.karpenter.sh/v1alpha1
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        kmsKeyID: *************
        volumeSize: 100Gi
        volumeType: gp2
    instanceProfile: *************
    kind: AWS
    securityGroupSelector:
      aws-ids: *************
    subnetSelector:
      Name: '*private-us-west-2*'
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: karpenter.k8s.aws/instance-size
    operator: In
    values:
    - 4xlarge
    - 8xlarge
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - m5
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-west-2a
    - us-west-2b
    - us-west-2c
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  ttlSecondsAfterEmpty: 1800
  ttlSecondsUntilExpired: 86400
````
Stuck nodes 
````
ip-10-136-149-112.us-west-2.compute.internal   Ready,SchedulingDisabled   <none>   11d     v1.21.14-eks-ba74326   default      us-west-2c
ip-10-136-71-188.us-west-2.compute.internal    Ready,SchedulingDisabled   <none>   11d     v1.21.14-eks-ba74326   default      us-west-2b
````

Logs (Filtered with the node hostname `ip-10-136-149-112.us-west-2.compute.internal`)
````
2022-08-29T15:29:05.325Z	INFO	controller.termination	Deleted node	{"commit": "5edcce3", "node": "ip-10-136-149-112.us-west-2.compute.internal"}
2022-08-22T20:58:22.851Z	INFO	controller.termination	Cordoned node	{"commit": "5edcce3", "node": "ip-10-136-149-112.us-west-2.compute.internal"}
2022-08-22T20:57:01.151Z	INFO	controller.termination	Cordoned node	{"commit": "5edcce3", "node": "ip-10-136-149-112.us-west-2.compute.internal"}
2022-08-22T20:56:27.916Z	INFO	controller.termination	Cordoned node	{"commit": "5edcce3", "node": "ip-10-136-149-112.us-west-2.compute.internal"}
2022-08-22T20:54:35.558Z	INFO	controller.termination	Cordoned node	{"commit": "5edcce3", "node": "ip-10-136-149-112.us-west-2.compute.internal"}
2022-08-22T20:51:12.990Z	INFO	controller.termination	Cordoned node	{"commit": "5edcce3", "node": "ip-10-136-149-112.us-west-2.compute.internal"}
2022-08-19T01:09:23.032Z	INFO	controller.termination	Cordoned node	{"commit": "5edcce3", "node": "ip-10-136-149-112.us-west-2.compute.internal"}
2022-08-19T01:09:23.001Z	INFO	controller.node	Triggering termination for expired node after 24h0m0s (+1.05637ms)	{"commit": "5edcce3", "node": "ip-10-136-149-112.us-west-2.compute.internal"}
2022-08-18T01:09:23.858Z	INFO	controller.provisioning.cloudprovider	Launched instance: i-08ea15ad5c42a0a83, hostname: ip-10-136-149-112.us-west-2.compute.internal, type: m6a.4xlarge, zone: us-west-2c, capacityType: on-demand	{"commit": "5edcce3", "provisioner": "default"}
````
Note: The delete log line comes after we manually force delete the pod.

**Comment by bwagner5** [comment]
It sounds like for your use-case a global force would be sufficient, is that accurate?   Another potential option would be to switch this based on a node label which could be propagated out via a Provisioner or set (/ removed) in an ad-hoc manner.

**Comment by nonoswz** [comment]
Yes, for our use case the global one would be fine. I guess It might be safer to configure this per provisioner though for other use cases.

**Comment by njtran** [comment]
Hey @nonoswz, there is another issue here https://github.com/aws/karpenter/issues/1532 which requests a `karpenter.sh/safe-to-evict` annotation that users can put on pods so Karpenter can terminate nodes with more than 0 pods to terminate with `ttlSecondsUntilEmpty`. This could also be expanded into the termination controller where we will evict pods that have the `safe-to-evict` annotation, which seems like would fit your use-case. Would this work?

**Comment by nonoswz** [comment]
@njtran We would prefer the opposite case actually. Meaning all pods are safe to be evicted unless they have a specific annotation (which we can do with `karpenter.sh/do-not-evict`). So we would still prefer to have a `--force` mechanism we could enable. 

Our main reason is that pods in our environments might be created by different teams that might not respect that annotation, so it might still block our nodes to expire.

**Comment by iAnomaly** [comment]
Can someone please reopen this? We are currently evaluating Karpenter to replace Cluster Autoscaler and this was the wrong decision for default behavior IMO. We greatly prefer the previous behavior in https://github.com/aws/karpenter/pull/2092.

To @nonoswz 's point, at the very least this behavior should be gated behind a force flag or some opt-in behavior; not the default. We have many "controllerless" pods created by various orchestrators outside Kubernetes itself like Airflow, GitLab, Jenkins, etc. that all manage the Pod lifecycle directly. As was covered in https://github.com/aws/karpenter/issues/2088, both `kubectl drain` and Cluster Autoscaler default to NOT deleting controllerless Pods for this reason: as a cluster operator I cannot know if they all:
1. Handle termination gracefully
2. Can handle rescheduling
3. Can pickup/resume where left off for long running workloads (think Airflow and CI)

It's not realistic or scalable for us to go annotate `karpenter.sh/safe-to-evict` across all these different orchestrators and systems to prevent this behavior.

While I appreciate the sentiment in...
>Per Kubernetes documentation, the use of naked pods should be avoided if possible and Karpenter should reinforce that recommendation. There should be no assumption of reliability or stability when naked pods are used given an involuntary node interruption can cause the pod to go away and not be recreated.

...Karpenter's consolidation is not involuntary and will occur orders of magnitude more often than a true involuntary node failure.

Thank you!

**Comment by ellistarn** [comment]
For pods that cannot tolerate disruption like this, can you define a pod disruption budget?

**Comment by FernandoMiguel** [comment]
@iAnomaly besides PDB, you can also use something kyverno to add the annotation

**Comment by iAnomaly** [comment]
> Apologies for a short response (mobile), but for pods that cannot tolerate disruption like this, can you define a pod disruption budget?

No, these are heterogeneous workloads not pools/groups of homogenous ones which PDBs are built for. We would need a separate PDB for every single Pod that is controllerless with `.spec.minAvailable: 1` and we have hundreds. Also note the documentation for PDB states:
>Before you begin
> * **You are the owner of an application running on a Kubernetes cluster that requires high availability.**
> * You should know how to deploy [Replicated Stateless Applications](https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/) and/or [Replicated Stateful Applications](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/).
> * You should have read about [Pod Disruptions](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/).
> * You should confirm with your cluster owner or service provider that they respect Pod Disruption Budgets.

We are not the owner of these applications or their Kubernetes executors. Even if our workloads were homogenous and we could use PDBs, the applications could change their labels at any time without warning and break our selectors.


> @iAnomaly besides PDB, you can also use something kyverno to add the annotation

A mutating webhook is a very heavy workaround to what should be a global opt-in/out-out feature of Karpenter.


I appreciate the brainstorming here but I'm not looking for workarounds, I'm explaining as a user why I think this was not only the wrong decision but also partly ignored the original feature request/change from another user (@nonoswz) to gate this (which we completely agree with) instead of unilaterally changing this behavior from what it was perviously.

If reverting this latest behavior won't be considered and doesn't even seem to be on the table for discussion (reopening the issue, discussing pros/cons instead of workarounds), could an opt-out flag or option at the Provisioner level instead of just the Pod annotation level be added to instead please?

**Comment by iAnomaly** [comment]
> > If reverting this latest behavior won't be considered and doesn't even seem to be on the table for discussion
> 
> Happy to reopen and discuss this issue.

Thank you for reopening @ellistarn. Really appreciate it.
> > I appreciate the brainstorming here but I'm not looking for workarounds
> 
> Brainstorming and understanding the root cause of the issue are one in the same here, I think. In my experience and from discussions with many customers, controllerless pods are an exceptional case. It's simply not the case there are are an indefinite number of them in every cluster. They need to be carefully managed and identified, since they do not conform to existing k8s reliability mechanisms.
> 
> Can you provide more information about the full set of controllerless pods you're running in your clusters, and why they're proliferating so broadly?

Airflow, Jenkins, GitLab and I'm sure many other Kubernetes executors all work in this way. They create controllerless Pods on demand for each unit of work and typically don't have pause/resume capabilities for that unit of work if interrupted. I say typically because Airflow tasks could theoretically be written in such a way where they could recover or pickup where they left off depending very heavily on the implementation specifics and an autoscaling solution like Karpenter shouldn't make those assumptions.
> I was imagining that you may be able to define a namespace-wide PDB to cover a well known set of exceptional pods that cannot tolerate disruption, whether you're using Karpenter consolidation, or other means of replacing nodes (e.g. mng upgrade).

See the [PDB doc section on bare/controllerless Pods](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors): even if we apply a PDB namespace-wide (by omitting any selector at all), only `.spec.minAvailable` is supported and not `.spec.maxUnavailable` where we would need the latter set to `.spec.maxUnavailable: 0` to ensure none of these Pods are disrupted. This also assumes we have all our controllerless Pods constrained to namespaces without any other types of Pods (which we don't).

**Comment by ellistarn** [comment]
> Airflow, Jenkins, GitLab and I'm sure many other Kubernetes executors all work in this way. They create controllerless Pods on demand for each unit of work and typically don't have pause/resume capabilities for that unit of work if interrupted. I say typically because Airflow tasks could theoretically be written in such a way where they could recover or pickup where they left off depending very heavily on the implementation specifics and a cluster level autoscaling solution like Karpenter shouldn't make those assumptions.

Are you facing these issues, or is this more of a theoretical design concern?

**Comment by iAnomaly** [comment]
> 



> > Airflow, Jenkins, GitLab and I'm sure many other Kubernetes executors all work in this way. They create controllerless Pods on demand for each unit of work and typically don't have pause/resume capabilities for that unit of work if interrupted. I say typically because Airflow tasks could theoretically be written in such a way where they could recover or pickup where they left off depending very heavily on the implementation specifics and a cluster level autoscaling solution like Karpenter shouldn't make those assumptions.
> 
> Are you facing these issues, or is this more of a theoretical design concern?

This issue is singlehandedly blocking our adoption of Karpenter over Cluster Autoscaler.
> 
> > See the [PDB doc section on bare/controllerless Pods](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors): even if we apply a PDB namespace-wide (by omitting any selector at all), only .spec.minAvailable is supported and not .spec.maxUnavailable where we would need the latter set to .spec.maxUnavailable: 0 to ensure none of these Pods are disrupted. Maybe I could set .spec.minAvailable to some ridiculously large value but that feels like a hack on whats is already a hack: trying to manage PDB for apps you don't maintain/own. This also assumes we have all our controllerless Pods constrained to namespaces without any other types of Pods (which we don't).
> 
> Thanks for this -- this makes sense. I suppose if you knew the n use cases where pods were created, you could create PDBs for them. It strikes me that it must be challenging to define PDBs for batch workloads (using jobs), not something I've done before.
> 
> Have you seen #1302 ? This could allow you to block termination of a node for any reason other than emptiness. Of course, this means running separate capacity for job and deployments workloads, but that may be acceptable for many use cases.

I haven't but we don't want to block at the node level or need scheduled deprovisioning. The existing Expiration/TTL feature is sufficient for our needs around time based deprovisioning.

**Comment by ellistarn** [comment]
> This issue is singlehandedly blocking our adoption of Karpenter over Cluster Autoscaler.

Just so I understand, you're using Gitlab, Airflow, and Jenkins. Each of them are creating controllerless pods AND you don't have the ability to specify do-not-evict on them?

**Comment by jonathan-innis** [comment]
Adding on to what @ellistarn said, can you inject annotations into the pods that Gitlab, Airflow, and Jenkins create? I think all of these orchestrators have mechanisms to inject annotations into the generated pods (linked the docs for each):

1. Gitlab: https://docs.gitlab.com/runner/executors/kubernetes.html#other-configtoml-settings
2. Airflow: https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/kubernetes.html#pod-mutation-hook
3. Jenkins: https://www.jenkins.io/doc/pipeline/steps/kubernetes/#podtemplate-define-a-podtemplate-to-use-in-the-kubernetes-plugin

**Comment by ellistarn** [comment]
Sorry to hear you're frustrated. I assure you, we really are trying to understand the issue and synthesize the feedback against everything we hear from customers of all kinds.

This case is tricky, since we've heard equally impassioned feedback in the opposite direction about controllerless pods blocking node upgrade (security) and impacting cost. In your case, it would impact availability or cause you operational toil. 

There are kubernetes users of all perspectives who want configuration at the pod level, node level, or global to the cluster. We have it at the pod level today. I hesitate to provide this as a karpenter global feature, since we find that the combinatorial expansion of global flags can make it quite challenging to debug issues and add new functionality. 

I could potentially see this rolling up into an eviction policy on https://github.com/aws/karpenter/issues/1302. We'd likely want to address requests for force eviction after a ttl, which is a similar tension between application and operator concerns. I've asked @njtran to deep dive this in his upcoming design.

**Comment by billrayburn** [comment]
Closing. Please open new issue to track this request to change current behavior.
