### ISSUE TITLE
Pods are not scheduled on the nodes that were added by Karpenter

### ISSUE THREAD

**Issue by liorfranko** [aws/karpenter#2453]
## Version

**Karpenter**: v0.16.0

**Kubernetes**: v1.20

## Expected Behavior
A pending pod should always be scheduled on the designated node launched by Karpenter.

## Actual Behavior
When a pod is pending, Karpenter launches a new node to match the pending pod; during the boot time of the node, there is newly available capacity on a different node, and the pending pod is being scheduled on the newly available capacity, the node that was added to the cluster is consolidated.

In current behavior, when decreasing the CPU/Memory of pods, there are many movements of pods and the end result of the capacity in the cluster is less optimized.

## Steps to Reproduce the Problem
Take a simple deployment with AntiAffinity, that each pod should be deployed on a different node.
Start with CPU request of 40.
Four pods will be deployed on four 12XL nodes.

1. Decrease CPU request to 4.
2. Four small pods will be pending.
3. Karpenter will add four small nodes that match CPU request of 4.
4. In the meantime the old pods are terminated.
5. There is new capacity on the old nodes and the AntiAffinity rule does not block.
6. The small pods will be deployed on the big nodes.
7. The small nodes are Ready.
8. The small nodes are consolidated.

We're using Spot instances, so in the above scenario, we're left with small pods deployed on big nodes.
In other scenarios, the end result is more optimal, but there are too many pod movements.

**Comment by tzneal** [comment]
We can't force a pod to schedule on a particular node.  Karpenter used to bind pods to nodes which did this forcing, but it caused other problems that there aren't any good solutions to.  The problem here is that the default deployment strategy creates 25% new pods, which can't schedule on existing nodes due to anti-affinity.  Karpenter launches new nodes to handle these, but when the old pods are evicted, kube-scheduler then schedules any pending pods to them that it can.

If this is a common scenario (i.e. updating a deployment with a self anti-affinity to reduce it's resource requests by a large amount), you can get somewhat, but still not reliably better behavior by using a specific deployment strategy:

```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
```

This causes all of the replacement pods to be created before the old pods are deleted.  It's not reliably better behavior though as the new nodes don't come up at the same time which allows an old pod to be evicted from a large node and be replaced with a new pod.

As you've indicated, with on-demand nodes the situation will resolve itself as we replace the larger nodes with smaller ones.  

Is there a use case for making large reductions in resource requests for a deployment with self anti-affinity?  It's the combination of these factors that is causing this to occur.

**Comment by liorfranko** [comment]
I know how to workaround it, but I don't think it's the right solution; even with on-demand instances, we will still have many pod movements on the cluster, which is not ideal on large scales.

As for our use-case, running with self anti-affinity is a Kubernetes best practice for running on Spot instances to reduce the blast radius during Spot interruptions.
And increasing/decreasing the resources are operations done by the service owners, for example when they handle bursts of traffic.

> We can't force a pod to schedule on a particular node. Karpenter used to bind pods to nodes which did this forcing, but it caused other problems that there aren't any good solutions to

Can you share what problems it caused?
Maybe it's better to solve the problems caused by forcing the scheduling?
>

**Comment by tzneal** [comment]
Other ways of reducing blast radius include horizontally scaling the number of pods and either limiting your maximum node size or using a topology spread constraint with a larger maxSkew value to limit the blast radius.  In that scenario decreasing the number of pods would be an option instead of decreasing the resource requests.  This may not work in your particular situation though depending on your application.

Part of the issue is that you have a very specific desired outcome (i.e. I want to reduce a deployment's resource requests by 90% and have each pod moved once to a smaller node), and kube-scheduler/Karpenter aren't aware of that intent.  For on-demand nodes it will eventually work due to node replacement, but since consolidation works generically by making single node changes to your cluster to reduce cost it will take some time to achieve the result.

You can however provide more information to kube-scheduler and Karpenter that let it know about your intent that the replacement smaller pods only run on smaller nodes.  If when you reduce the CPU request from 40 to 4, you also add a requirement of:
```yaml
  - key: karpenter.k8s.aws/instance-cpu
    operator: Lt
    values:
    - "9"
```

`kube-scheduler` won't schedule that pod to the existing nodes as their CPU count is >= 9 and must wait until the smaller nodes become ready.


The problems that occur when binding pods to node include:
- often times slower overall pod startup time
- general flakiness with extended resource types (i.e. GPUs) as kubelet zeroes those resources out upon startup which cause the bound pod to be evicted
- much slower pod startup time when using SGPP
- masks any issues with the Karpenter scheduler

**Comment by liorfranko** [comment]
I see.
Ok, I'll implement one of the workarounds.
Thank you so much for your quick and informational responses!
