### ISSUE TITLE
blockDeviceMappings location changed

### ISSUE THREAD

**Issue by MaciejKucia** [aws/karpenter#2454]
**Is an existing page relevant?**
https://karpenter.sh/v0.16.1/aws/provisioning/#block-device-mappings

**What karpenter features are relevant?**
Provisioner CRD schema

**How should the docs be improved?**
The `blockDeviceMappings` was moved from `spec` to `spec.provider`

Please confirm if this is intented and I can open PR.

**Comment by bwagner5** [comment]
@MaciejKucia the spec is supposed to refer to the AWSNodeTemplate now rather than the Provisioner. 

It used to be that blockDeviceMappings were nested under `spec.provider.blockDeviceMappings`. They still exist at that location, but we recommend using the AWS Cloud Provider's NodeTemplate CRD instead which is pointed to in the provisioner at `spec.providerRef` and then under the AWSNodeTemplate blockDeviceMappings are nested under `spec.blockDeviceMappings`.

**Comment by MaciejKucia** [comment]
@bwagner5 I have made changes per your comment please let me know if I can update this somehow else. Thanks!
