### ISSUE TITLE
Unable to locate any tags in provided repository: oci://public.ecr.aws/karpenter/karpenter

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/karpenter#2619]
### Version

__Karpenter Version:__ v0.17.0

__Kubernetes Version:__ 
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.10-eks-15b7512", GitCommit:"cd6399691d9b1fed9ec20c9c5e82f5993c3f42cb", GitTreeState:"clean", BuildDate:"2022-08-31T19:17:01Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Expected Behavior

for `data "helm_template"` to return the latest helm chart

### Actual Behavior

```hcl
│ Error: Unable to locate any tags in provided repository: oci://public.ecr.aws/karpenter/karpenter
│
│   with module.base_system.data.helm_template.karpenter_chart_version_latest,
│   on .terraform/modules/base_system/chart_versions.tf line 110, in data "helm_template" "karpenter_chart_version_latest":
│  110: data "helm_template" "karpenter_chart_version_latest" {
```

### Steps to Reproduce the Problem

apply the following terraform code snippet
```hcl
data "helm_template" "karpenter_chart_version_latest" {
  name       = "karpenter"
  chart      = "karpenter"
  repository = "oci://public.ecr.aws/karpenter"
}
```

the previous version, pointing to the old repo, works as expected
```hcl
data "helm_template" "karpenter_chart_version_latest" {
  name       = "karpenter"
  chart      = "karpenter"
  repository = "https://charts.karpenter.sh"
}
```

### Resource Specs and Logs

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Since we switched the helm chart to an OCI repo which doesn't have an `index.yaml` like a traditional helm repo, discovery of the latest version is broken.  There's some chatter on reimplementing search for OCI which may eventually make its way to installing latest again https://github.com/helm/helm/issues/11000

We may want to publish a "latest" helm chart so that functionality is matched with the old repo. I'm not sure if there are implications when doing that. `latest` tags are generally frowned up for containers because of caching mechanisms, so we'd need to look how this is handled with helm.  Right now, I think your best bet is to hardcode the version of Karpenter you want to install. 

This command lists the semver tags published to the repo, so you may be able to pull this info to automatically update helm charts:

```
skopeo list-tags docker://public.ecr.aws/karpenter/karpenter | grep '"v[0-9]\+\.[0-9]\+\.[0-9]\+\"' | tr -s " " | cut -d "\"" -f2
```

In general, the latest github release tag should always be published in the helm repo which is probably easier to pull. There may be some timing delay on a release if you would happen to hit it just right, but would only be a few seconds or minutes.

**Comment by FernandoMiguel** [comment]
Oh we pin all our charts.
This is just a nice to have for all charts to pull the latest version, so we know we are behind, and to do a diff of changes.

**Comment by hamishforbes** [comment]
> Oh we pin all our charts. This is just a nice to have for all charts to pull the latest version, so we know we are behind, and to do a diff of changes.

A `latest` tag would also be very useful for those of us using [FluxCD](https://fluxcd.io/flux/components/source/ocirepositories/) to install Karpenter.

Flux separates the concept of a Helm repository and a Helm release into independent resources, you can have a many to 1 relationship between releases and repositories.

The normal way to do this would be to have a single `OCIRepository` resource pointing at latest, and then you specify `v0.18.0` (or whatever) in the `HelmRelease` version.

Without a `latest` we have to specify the `v0.18.0` in the `OCIRepository` ref field and the `HelmRelease` version field.

Obviously you're unlikely to actually be installing multiple instances of Karpenter, but it does break the normal use case (and my automation...) for using Flux.
