### ISSUE TITLE
Karpenter is unable to get current on-demand pricing in GovCloud (us-gov-west-1)

### ISSUE THREAD

**Issue by snorlaX-sleeps** [aws/karpenter#2706]
### Version

__Karpenter Version:__ v0.18.0

__Kubernetes Version:__ v1.22

### Expected Behavior

Karpenter should be able to get current on-demand pricing at startup in the GovCloud partition, as it does in the commercial partition.

### Actual Behavior

Karpenter outputs an error claiming to be unable to get current pricing in the region and defaults back to the pricing created when the image was built (`2022-09-23T20:07:54Z`) which is potentially not region specific

According to the documentation provided by AWS there are only certain valid regions for the new pricing API, but they provide information for all regions including GovCloud:
```
The new functions are available now and you can start using them today in the US East (N. Virginia) and Asia Pacific (Mumbai) Regions to access metadata and price listings for all public AWS Regions and **AWS GovCloud (US)**, at no charge.
```
[Blog Post](https://aws.amazon.com/blogs/aws/aws-price-list-api-update-new-query-and-metadata-functions/)

### Steps to Reproduce the Problem

Deploy Karpenter in a GovCloud based cluster. Logs appear during startup for all controller pods (pre leader election)

### Resource Specs and Logs

Logs:
```
2022-10-19T17:45:22.374Z	INFO	controller.aws.pricing	updated spot pricing with 558 instance types and 879 offerings	{"commit": "1d8eb34"}
I1019 17:45:22.464565       1 leaderelection.go:248] attempting to acquire leader lease <cluster_name>/karpenter-leader-election...
2022-10-19T17:45:22.521Z	ERROR	controller.aws.pricing	updating on-demand pricing, UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 6e6bdd64-2361-4c8b-bd66-5fd2f35869de; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: c21f933e-236d-4028-8b7f-42e98d06dbb4, using existing pricing data from 2022-09-23T20:07:54Z	{"commit": "1d8eb34"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by fpedrini** [comment]
Hello,

I was peeking through the code about this, and I think that the problem is that the [client for the pricing api](https://github.com/aws/karpenter/blob/main/pkg/cloudproviders/aws/cloudprovider/pricing.go#L81-L93) reuses the same client session the rest of the code uses to do its thing and that it's tied to the IAM role linked to the karpenter service account.

This is clearly expected and working fine for AWS Commercial regions, but breaks in separate AWS partitions.

We have solved a similar issue (i.e. a pod in a govcloud cluster that needs to access endpoints and resources only available in commercial regions) by setting up roles in commercial accounts that allow `sts:AssumeRoleWithWebIdentity` via the EKS cluster OIDC provider as detailed in the [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html).
When a service account is configured in such a way, the pod is effectively running with the permissions associated with the commercial-region role (assuming the right AWS_REGION env var is set), but this means that the pod has no permissions to perform calls on the original account.

This works well for pods that just need access to the commercial region and requires no further permissions in the original account (we use this for external-DNS to add records in public DNS zones), but the Karpenter controller requires various `ec2:*` permissions to be able to do its job, and since the pricing client is an integral part of the controller component, it is not possible to "simply" change the IAM role and leverage the OIDC federation.

I believe that the solution would be to refactor the pricing client code to be able to spawn a new AWS client using a separate role from the one mentioned in the ServiceAccount.
That role ARN would be controlled via a cli option or environment variable, for example `PRICING_CLIENT_AWS_ROLE_ARN`.
The code has already logic to figure out the right pricing endpoint based on the region name, I think that might be fine, just the Session object needs to change.
If the cli option/env var are set the pricing client should use that role and fallback on the ServiceAccount-attached role otherwise.

This will allow user running Karpenter in Govcloud to set up a federated role in one of their commercial account (likely the paired commercial account) with the right `pricing:*` IAM permissions, so that the controller can still run within the context of the original account (so it's able to spin up instances and the like) but the pricing client is able to "teleport" into a commercial role and access the pricing API correctly.

The other alternative I see is to extract the pricing client into a separate pod that can run with a separate service account, but that sounds a lot more involved.

**Comment by bwagner5** [comment]
Thanks for the detailed comment!  Yeah I would definitely agree that adding a `PRICING_CLIENT_AWS_ROLE_ARN` is probably the best way to go even if it is a little messy itself.

**Comment by AMHesch** [comment]
The other alternative could be to utilize the [bulk APIs](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-ppslong.html) to pull the data en masse instead of using the query API. This would alleviate the complexity of the additional role and having to set up cross-partition identity.

**Comment by balusarakesh** [comment]
FYI: this issue is still happening even after using the image `public.ecr.aws/karpenter/controller:v0.27.0`
```
2023-03-15T19:02:44.253Z	ERROR	controller.aws.pricing	updating on-demand pricing, UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: ; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: , using existing pricing data from 2023-02-27T15:52:29Z	{"commit": ""}
```

**Comment by tzneal** [comment]
Yes, this issue still occurs since there is no endpoint, however we do have generated pricing baked into the product at https://github.com/aws/karpenter/pull/3336/files

**Comment by vstthomas** [comment]
I'm still seeing this behavior:

```log
{"level":"ERROR","time":"2023-12-29T01:32:02.192Z","logger":"controller.pricing","message":"retreiving on-demand pricing data, UnrecognizedClientException: The security token included in the request is invalid\n\tstatus code: 400, request id: 5d038231-2332-4aef-b888-dbe037b60dc2; UnrecognizedClientException: The security token included in the request is invalid\n\tstatus code: 400, request id: a0b548d6-4833-4883-84ac-84db45806e7b","commit":"1072d3b"}
```

What's the status on this one?
