### ISSUE TITLE
Why Enable VPC CNI Prefix Assignment Mode if Using Smaller Instance Types?

### ISSUE THREAD

**Issue by kevarr** [aws/karpenter#2759]
### Is an existing page relevant?

https://github.com/aws/karpenter/blob/main/website/content/en/v0.18.1/tasks/pod-density.md?plain=1#L23-L25

### What karpenter features are relevant?

Control Pod Density

### How should the docs be improved?

Hello,

The [Control Pod Density](https://github.com/aws/karpenter/issues/new?assignees=&labels=Documentation&template=docs-request.yaml) notes that when using small instance types, it may be necessary to enable prefix assignment mode in the AWS VPC CNI plugin to schedule more pods per node.

Why is this being suggested? Is it the possible that Karpenter may schedule >`maxPods` to a smaller node?

Thanks!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
This recommendation is aimed at a more static maxPods value rather than scaled based off of the max IPs able to be allocated to a node. The [K8s scalability docs](https://kubernetes.io/docs/setup/best-practices/cluster-large/) recommend a max of 110 pods per node. Some smaller instance types are unable to attach 110 + 1 (node IP) IPs to a node so enabling Prefix Delegation can help in situations where a small node can't allocate the static number of max pods you have configured. 

Karpenter doesn't directly schedule to nodes, kube-scheduler is still in-charge of the pod bindings and will not bind pods over the maxPods value on the node.
