### ISSUE TITLE
Unable to call webhook while creating provisioner

### ISSUE THREAD

**Issue by starsunny** [aws/karpenter#2983]
### What karpenter features are relevant?

Full Error:

Error from server (InternalError): error when creating "od-provisioner.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": Post "https://karpenter.karpenter.svc:443/?timeout=10s": x509: certificate signed by unknown authority
Error from server (InternalError): error when creating "od-provisioner.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": Post "https://karpenter.karpenter.svc:443/?timeout=10s": x509: certificate signed by unknown authority

Tried:

Tried deleting and recreating the secret, Tried safe installation with the helm files.
Tried NACL, SG rules, associations, tagging, selectors and all but couldn't find anything.
The same installing method is working in another clusters but not working for the one cluster.

### How should the docs be improved?

Couldn't fine any debug doc for this.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by funes79** [comment]
In the latest version 0.19.3 I have a similar error
```
2022-12-05T13:05:25.492Z ERROR controller Reconciler error {"commit": "683d4b0", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "Provisioner": {"name":"autoscale-default"}, "namespace": "", "name": "autoscale-default", "reconcileID": "266e1678-d072-488c-9583-c056b090d224", "error": "Internal error occurred: failed calling webhook \"defaulting.webhook.provisioners.karpenter.sh\": failed to call webhook: the server rejected our request for an unknown reason"}
```

**Comment by maximmold** [comment]
I am having an issue as well with a connection refused error presumably in 0.19.3 presumably due to hostNetwork port overriding being broken in this PR. https://github.com/aws/karpenter/pull/2728.  This documentation describes the environment variable WEBHOOK_PORT which can override the default. Even with this set, it still uses the default of 8443.

We are using `hostNetwork: true` to get around issues with the control plane contacting the webhook. When using cilium, the control plane doesn't seem to be able to reach the service otherwise.

The PR mentioned about seems to indicate that the changes were still a work in progress and prematurely merged. Perhaps this is related to the original issue?

**Comment by noony** [comment]
I think I found what's the issue this [commit](https://github.com/aws/karpenter/commit/fc8beacdf806d52f3890a8dc6ff977edc654d93b#diff-aca5167a508bb2646bf05a51c743cf850d82fa44e2a427aa4091cefb32da80f5L67) removed the flag `-webhook-port` and now we use the env var WEBHOOK_PORT, but in karpenter-core env var is named PORT instead of WEBHOOK_PORT [here](https://github.com/aws/karpenter-core/blob/c90bcac0987e87b3807c333ebc97d3dd627e5b17/pkg/operator/options/options.go#L58)

The change in karpenter-core + bump of go mod should fix this issue (cc @ellistarn who made the initial migration)

**Comment by peteroruba** [comment]
Not sure if this is related to the issue discussed here, but I am seeing "Liveness probe failed: Get "https://10.139.164.169:8443/": remote error: tls: unrecognized name" (10.139.164.169 is the Karpenter Pod's IP). I am using Helm Chart Version 0.16.3

**Comment by jtgorny** [comment]
I'm seeing a similar issue in version 0.19.3, only mine isn't a certificate error. Mine is an address not allowed error.
`Error from server (InternalError): error when creating "./out/karpenter/provisioner.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.k8s.aws?timeout=10s": Address is not allowed`

I followed the troubleshooting steps [here](https://karpenter.sh/v0.19.3/troubleshooting/#failed-calling-webhook-defaultingwebhookprovisionerskarpentersh) only it seems these are outdated since the new chart doesn't have a dedicated webhook container.

**Comment by mukundmckinsey** [comment]
I am following the [doc](https://karpenter.sh/v0.20.0/getting-started/getting-started-with-eksctl/)  and facing the same issue with karpenter version 0.22.0:

```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.k8s.aws?timeout=10s": Address is not allowed
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.k8s.aws?timeout=10s": Address is not allowed
```

**Comment by mukundmckinsey** [comment]
> I confirmed that's the issue on my side, a temporary fix for version > 0.19.3 is :
> 
> ```
> controller:
>   env:
>   - name: PORT
>     value: "123-YOUR-PORT-VALUE"
> ```

Tried this and it did not help.

**Comment by jseiser** [comment]
> I am following the [doc](https://karpenter.sh/v0.22.0/getting-started/getting-started-with-eksctl/) and facing the same issue with karpenter version 0.22.0:
> 
> ```
> Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.k8s.aws?timeout=10s": Address is not allowed
> Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default/karpenter.k8s.aws?timeout=10s": Address is not allowed
> ```

Same issue here as well.  

```
2023-01-17T20:13:14.657Z info Kustomization/infrastructure.flux-system - Dispatching event: AWSNodeTemplate/karpenter/default dry-run failed, reason: InternalError, error: Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/?timeout=10s": x509: certificate signed by unknown authority
```

**Comment by BMonsalvatge** [comment]
Running into the same issue whenever trying to update the provisioners:
```
Internal error occurred: failed calling webhook "defaulting.webhook.provisioners.karpenter.sh": failed to call webhook: Post "https://karpenter.karpenter.svc:443/default-resource?timeout=10s": x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "karpenter.karpenter.svc")
```
Using Calico on EKS with `hostNetwork: true`.
