### ISSUE TITLE
Dynamic block device size

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter#3077]
### Tell us about your request

Right now the block device size is static, but it is a huge difference if you have a m5.large instance or a m5.16xlarge image... The first instance might host 5 containers, the last might host 200 containers.

Right now the block device size is static... i would like to see some base value and an additional value based on the node size (cpu/ram). A small instance might need 20GB disk volume, a big instance might need 1000GB disk volume.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Right now you have either too much storage or you have full file systems...

### Are you currently working around this issue?

Overprovisioning disks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Added this feature as a linked issue to the #2394. Can you 👍 that issue so that we track that you are requesting it?

I will say that we are tracking this request since there's been customer ask for it. There are some pre-reqs in the works right now (Machine CRD implementation #2944) that are blocking are ability to implement this immediately but it's a fast-follow that we want after we get the RFC node ownership implementation in.

**Comment by jonathan-innis** [comment]
I'm going to close this issue as a duplicate for now, please 👍 the other issue or add comments to #2394 about your specific use case.
