### ISSUE TITLE
Adjust  blockDeviceMappings volume  size depending on instance size.

### ISSUE THREAD

**Issue by oleksiytsyban** [aws/karpenter#3111]
### Tell us about your request

Is it possible to adjust volumeSize in AWSNodeTemplate blockDeviceMappings depending on an instance size. So 2x instance has 20 Gb volume, and 20x instance 200 Gb?

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

If AWSNodeTemplate has blockDeviceMappings with defined volumeSize, than both 2x instance and 24x instance will have same volume size. In 2x instance 2/3 of it is not in use, 24x instance can not use ins CPU and RAM because of luck of ephemeral storage.

### Are you currently working around this issue?

Currently I have to limit max instance size by CPU or RAM and use extra volume for instances.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Relates to #2390 and #2394. I think our thought around this is that the ideal behavior is that we don't have to think about instance volume size at all when scheduling. Ideally, it would be nice if the blockDeviceMappings scaled based on what the scheduler says is needed (that's what's covered in #2394). This isn't being directly addressed right now (there's some changes down the pipe that need to be done first), but it's something we're looking at prioritizing more and more as we hear more requests for it.

Can you 👍 #2394 since this is the original issue for this feature?

**Comment by jonathan-innis** [comment]
We're planning on handling this as part of #2394 so I'm going close this for now.
