### ISSUE TITLE
Add additional BottleRocket userdata options in AWSNodeTemplate

### ISSUE THREAD

**Issue by xeon22** [aws/karpenter#3166]
### Tell us about your request

Add additional bottlerocket userdata options such as:

```toml
[settings.dns]
search-list = ["svc.example.com", "example.com"]
[settings.kubernetes]
cluster-domain = "example.com"
```

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I have a cluster with a custom cluster-domain.  I cannot use karpenter on this cluster to provision nodes as it does not support the additional userdata settings on bottlerocket nodes to define the custom settings.

### Are you currently working around this issue?

Will continue to use cluster-autoscaler for that cluster with the custom domain defined.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by lucass4** [comment]
@ellistarn  correct me if I am wrong but I believe this is not needed since bottlerocket accepts the [`settings:*` ](https://github.com/aws/karpenter/pull/2081/files#diff-2fd580a7ca136c4070982cc80b7fe7e13c3ebeeb8a2bd4d80921f7de436b28c7R34)configuration.
This functionality was implemented in this PR https://github.com/aws/karpenter/pull/2081
