### ISSUE TITLE
Disabling consolidation via annotations

### ISSUE THREAD

**Issue by dudicoco** [aws/karpenter#3228]
### Is an existing page relevant?

https://karpenter.sh/v0.22.1/concepts/deprovisioning

### What karpenter features are relevant?

[This section](spec.consolidation.enabled) states that the `karpenter.sh/do-not-consolidate: "true"` annotation can be added in the provisioner spec in order to disable consolidation.

However, it is stated [here](https://karpenter.sh/v0.22.1/concepts/deprovisioning/#:~:text=Automated%20deprovisioning%20is%20configured%20through%20the%20ProvisionerSpec%20.ttlSecondsAfterEmpty%20%2C%20.ttlSecondsUntilExpired%20and%20.consolidation.enabled%20fields.%20If%20these%20are%20not%20configured%2C%20Karpenter%20will%20not%20default%20values%20for%20them%20and%20will%20not%20terminate%20nodes%20for%20that%20purpose.) and [here](https://karpenter.sh/v0.22.1/concepts/provisioners/#specconsolidation) that consolidation can be disabled by setting `consolidation.enabled: false` within the provisioner spec.

### How should the docs be improved?

Clarify on how consolidation should be disabled.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Sorry, the docs aren't really clear there. The provisioner spec setting controls consolidation overall for that provisioner.  You can also control it via an annotation on a node, which turns off consolidation for a single node only.  If you specify that annotation on the provisioner, it also turns it off for the provisioner since it applies that annotation to each node.  If you wanted, you could then remove the annotation for a single node to enable annotation for it.
