### ISSUE TITLE
Undocumented error metrics

### ISSUE THREAD

**Issue by dudicoco** [aws/karpenter#3263]
### Is an existing page relevant?

https://karpenter.sh/v0.22.1/concepts/metrics

### What karpenter features are relevant?

There are three error related metrics that are undocumented:
```
karpenter_deprovisioning_reconcile_errors_total
karpenter_provisioner_reconcile_errors_total
karpenter_metricscraper_reconcile_errors_total
```

We are trying to set up prometheus alert rules but it's hard to figure out on which of these we should alert on.

### How should the docs be improved?

Document these metrics, also more specifically:

What is the difference between `karpenter_deprovisioning_reconcile_errors_total` and `karpenter_provisioner_reconcile_errors_total`?

What is the `metricscraper`?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spring1843** [comment]
@dudicoco what version of Karpenter are you using?

**Comment by dudicoco** [comment]
@spring1843 `v0.22.1`

**Comment by jonathan-innis** [comment]
@dudicoco. You're correct that these should be properly documented. Right now, we're running into issues with our current code-gen pattern on metrics that's preventing us from adding these to the docs. Ideally, we'd like to fix our codegen so that it catches _all_ metrics that Karpenter owns that are exposed on the api-server. 

Alternatively, if we can come up with a way to codegen combined with manual changes in our `metrics.md` that would also work.

**Comment by dudicoco** [comment]
@jonathan-innis can you please elaborate on the differences between these different metrics?

**Comment by dudicoco** [comment]
@jonathan-innis ping

**Comment by jonathan-innis** [comment]
Hi @dudicoco. We have metrics that are auto-generated from our [`make docgen`](https://github.com/aws/karpenter/blob/main/hack/docs/metrics_gen_docs.go) task that are intended to be auto-discovered by scanning the code. Unfortunately, this code doesn't work well when there are variable names that are used inside of the metric registration process, so it misses some metrics that Karpenter actually publishes.

One (more robust) solution to this problem is to change the way that we do auto-generation here and instead grab metrics directly from the prometheus registry. This doesn't work perfectly right now since Prometheus doesn't return the metrics from the registry in a public function until the metrics are fired.

Ideally, we could create a decorator around the metric registration function that kept track of metrics for this auto-generation flow.

Alternatively, we can just continue to rely on our current auto-generation logic but allow manual changes to the [metrics doc](https://github.com/aws/karpenter/blob/main/website/content/en/preview/concepts/metrics.md) which is currently fully overwritten by the `make docgen`, though this could be changed to be more of an append action so that any manual changes aren't thrown away.

**Comment by billrayburn** [comment]
Closing, all metrics should auto-generated at this point.
