### ISSUE TITLE
AWS EBS Volume resizing

### ISSUE THREAD

**Issue by Aym3nTN** [aws/karpenter#3574]
I'm using Karpenter to auto-scale a cluster of runners; occasionally my build jobs fail due to lack of storage in the node where the pod is running.

I know that one can increase EBS volume size on-the-go and without downtime; but scaling down is not possible, but I don't think this would be a problem because the whole EC2 instance spun by Karpenter will be shutdown when not being in use after certain TTL.

So in order to respond to a spike in demand or to adjust to a new workload need, I suggest that we instruct Karpenter to modify the existing AWS EBS volume by making the appropriate API calls in order to, for example, incrementally increase the volume if certain threshold is hit.

Let me know, first, if this something that we can get around easily, or, second, if we need to discuss more the use case and add it as a feature.

**Comment by FernandoMiguel** [comment]
seems that all you have to do, is set the ebs sze that meets your requirements
https://github.com/aws/karpenter/blob/ffc77057/examples/provisioner/multiple-ebs.yaml#L40

**Comment by runningman84** [comment]
The idea is that karpenter increasing the volume after reaching some limit instead of having a bigger ebs volune for all nodes all the time...

In one hand I like the idea on another hand I see multiple problems:
* ebs volumes cannot be increased multiple times within a short timeframe (or is this possible today)
* the increase might not happen fast enough
* a better solution might be to limit the space for each build job or to attach some unlimited size storage like EFS

**Comment by Aym3nTN** [comment]
@FernandoMiguel I can always attach a big volume on new instances but that's the not point here, I want to perform an "in-place" scale out. 
@runningman84  true, it might sound challenging as EBS size increase might not happen fast enough and not possible to scale back in since you can't just reduce the size of an EBS volume on-the-go (there are some steps to do which will take too much time and not worth scaling). For my case, I don't care if I can't scale back in since the EC2 will be killed once the build job finishes executing but I want to anticipate disk increase whenever I reach like 70%. 

What do you think?

**Comment by FernandoMiguel** [comment]
I don't think karpenter is the place to address this.
it should be a different operator or EBS CSI sort of thing.
Karpenter is more about compute capacity, AFAIK

**Comment by bwagner5** [comment]
I agree that Karpenter is probably not the right place for this type of dynamic scaling feature of volumes at runtime. I've explored doing this and ran into a few problems that make this not so trivial. 

1. You can only modify volumes every 6 hours
2. In-place grow-fs needs to be coordinated on-instance - this needs a lot of testing to see if this is safe and requires a DaemonSet component

I was also thinking about using LVM or a RAID so that we could attach disks to increase disk size or IOPs when the disk size can't be modified through EBS APIs.

**Comment by jonathan-innis** [comment]
Closing since this is related to #2394
