### ISSUE TITLE
Accept base64 encoded userData for AWSNodeTemplate

### ISSUE THREAD

**Issue by thelabdude** [aws/karpenter#3593]
### Tell us about your request

The userData section of my AWSNodeTemplate looks like a huge jumbled mess with embedded `\n` ... I think it would be a nice to accept base64 encoded string here instead.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

see above ^^

### Are you currently working around this issue?

see above ^^

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by thelabdude** [comment]
sounds like some folks in this community are opposed to making `userData` section easier to populate using IaC like Pulumi so I'll just close this

**Comment by ellistarn** [comment]
@thelabdude we're open minded, but we want to make sure karpenter is the root cause of the issue. Generally I agree with Jonathan that we want to minimize API surface, but we also want karpenter to be a delight to use. 

Is it possible that there are changes to pulumi that could make this easier? Presumably there are other multiline string use cases where it's difficult to template things. Are we misunderstanding something though?
