### ISSUE TITLE
Improve Existing Cluster Karpenter Installation Docs

### ISSUE THREAD

**Issue by srbharath** [aws/karpenter#3600]
### What karpenter features are relevant?

 Regarding the how to setup karpenter with existing k8s cluster which is set by kubeadm , the api versions are not supporting to create karpenter controller, machine template

### How should the docs be improved?

Improve the documentation regarding how to set up using existing on-prem cluster all the document are on eks, that good but incude existing cluster also

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
What version of K8s are you using?  Karpenter supports K8s versions 1.21+

**Comment by bwagner5** [comment]
We can't document all ways of installing Karpenter, but one of the fundamental differences is how Karpenter gets the AWS permission required since you can't use IAM Roles for Service Accounts (IRSA) in an on-prem setting. I would guess this is the thing you are running into. 

Karpenter uses the default credential chain for the aws-sdk-go, so you can specify credentials as env var secrets. 

- https://kubernetes.io/docs/concepts/configuration/secret/
- https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#:~:text=for%20additional%20information.-,Specifying%20the%20AWS%20Region,-When%20you%20specify
