### ISSUE TITLE
Karpenter does not use the correct pricing in some cases.

### ISSUE THREAD

**Issue by rwilliams-r7** [aws/karpenter#3672]
### Version

__Karpenter Version:__ v0.27.1

__Kubernetes Version:__ v1.24 (EKS)

### Expected Behavior

Karpenter should consider AWS Savings Plans + other potential discounts that may be applied to an organization. 

### Actual Behavior

Karpenter uses the EC2 API to pull the on-demand prices. Karpenter does not allow the use of config to take into account discounts that may be applied to EC2 on-demand cost to help it make the correct choice. This is really important when dealing with spot and on-demand in the same provisioner. We have seen many cases when a spot has been chosen because the cost is less than the on-demand cost but it is more expensive than the on-demand cost when the discount is applied.

### Steps to Reproduce the Problem

Create a provisioner which has spot and on-demand.

### Resource Specs and Logs

n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Thanks for submitting the issue. We are aware that Karpenter doesn't integrate well with discount pricing for Reserved Instances (RIs) and Savings Plans (SPs). RIs are really difficult to integrate with since there isn't a real-time API for tracking usage. RIs are a billing discount that doesn't get applied until the end of the month. 

We have a recommendation to setup weighted provisioners where the first priority provisioner is for your RIs or SPs with resource limits based on the specific RI or SP. Once you breach the limit, Karpenter will move to the next priority provisioner which can include your spot instance pools.

https://karpenter.sh/v0.27.1/concepts/scheduling/#weighting-provisioners

There's an issue with consolidation using the weighted provisioner approach that is sub-optimal tracked here: https://github.com/aws/karpenter/issues/3578

Here's another issue tracking savings plans integration: https://github.com/aws/karpenter/issues/2259

I'd recommend adding any additional context you have and a 👍 on #2259 and #3578. I'll close this one as a duplicate, but feel free to reopen if you think this is something different from the other issues I linked.
