### ISSUE TITLE
interruptionQueueName

### ISSUE THREAD

**Issue by elitistphoenix** [aws/karpenter#3796]
### Is an existing page relevant?

https://karpenter.sh/preview/concepts/deprovisioning/#interruption

### What karpenter features are relevant?

interruptionQueueName documentation
This is mentioned a few times in different links but then I can't find actual documentation to create the SQS queue.

I know this was added in v0.19.

https://karpenter.sh/preview/concepts/deprovisioning/#interruption points to:
https://karpenter.sh/preview/getting-started/getting-started-with-karpenter/#create-the-karpenter-infrastructure-and-iam-roles

I also see this:
https://github.com/aws/karpenter/issues/2897#issuecomment-1322244895
Obviously that link in the post has expired info can be found here
https://github.com/aws/karpenter/blob/release-v0.19.x/website/content/en/v0.19.1/getting-started/getting-started-with-eksctl/cloudformation.yaml#L64-L71

### How should the docs be improved?

Some basic easy to find information on permissions and requirements to setup the aws.interruptionQueueName SQS.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
[#2897 (Commnet)](https://github.com/aws/karpenter/issues/2897#issuecomment-1322343648) @elitistphoenix Have you seen this comment on the post? I hope this gives you better context as to why it is not in the documentation.  Here is some information on the general way to create an [SQS queue](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/step-create-queue.html). As you can also see in the [documentation](https://karpenter.sh/preview/concepts/deprovisioning/#interruption), karpenter only needs the `aws.interruptionQueueName`.

**Comment by jonathan-innis** [comment]
>This is mentioned a few times in different links but then I can't find actual documentation to create the SQS queue.

We have the [CloudFormation template](https://karpenter.sh/v0.27.3/getting-started/getting-started-with-karpenter/cloudformation.yaml) for the latest version of Karpenter which has the Queue creation and the EventBridge rules in the template. 

Are you looking for more explicit callouts that this CloudFormation template is creating the queue for eventing?

**Comment by elitistphoenix** [comment]
Yes, in the getting started doco maybe something about how to manually create them. Also one of the recent docs on permissions for the IAM user doesn't mention those sqs permissions. It only got as far as the pricing:GetProducts.

**Comment by jonathan-innis** [comment]
> Also one of the recent docs on permissions for the IAM user doesn't mention those sqs permissions

Can you reference the doc you are talking about? I think the most recent cloudformation doc has these permissions?

**Comment by elitistphoenix** [comment]
https://karpenter.sh/v0.27.3/ and then search the page for sqs

**Comment by elitistphoenix** [comment]
also https://karpenter.sh/v0.27.3/getting-started/getting-started-with-karpenter/
search for sqs and nothing too

**Comment by jonathan-innis** [comment]
> search for sqs and nothing too

We were anticipating that the "Getting Started" experience would be for fresh installs and that the fact that we are enabling interruption and setting up the SQS/EventBridge as part of that bootstrapping experience is a bit of an implementation detail. Are you coming from trying to onboard an existing cluster onto interruption handling that has already been running Karpenter for some time?

**Comment by elitistphoenix** [comment]
Yes for one cluster a least.
Also for instance
https://karpenter.sh/v0.27.3/concepts/deprovisioning/#interruption => https://karpenter.sh/v0.27.3/getting-started/getting-started-with-karpenter/#create-the-karpenter-infrastructure-and-iam-roles
No mention of sqs only on mention of interruptionQueueName in the helm upgrade command line which is what I used and is where it started not working. I had to remove it.

**Comment by jonathan-innis** [comment]
Got it. This definitely makes sense. Letting @chrisnegus take a look at this and see where we can surface more information on the interruption queue in the docs.

**Comment by elitistphoenix** [comment]
Thanks!

**Comment by llynch-activecampaign** [comment]
Hi, after creating SQS, Eventbridge, permissions and setting interruptionQueueName=new-sqs, how do I verify that karpenter is handling the terminations gracefully? I see messages in the SQS queue and I'm checking karpenter logs.
I see "controller.deprovisioning	deprovisioning via "consolidation"" 
What log message is output when terminating because of a Spot interruption for example, that would prove to me that I have configured the karpenter node termination handler correctly?
Thank you.

**Comment by tgmatt** [comment]
For anyone else looking for this information (since it still doesn't seem to exist on the website), looking at the terraform code for the eks module gives some clues that you can work from. See [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/karpenter/main.tf#L190-L298).

**Comment by chrisnegus** [comment]
We added a new page that details the cloudformation.yaml used in the Karpenter Getting Started guide. It will be published with v0.32, but is currently available in preview here: [Cloudformation](https://karpenter.sh/preview/reference/cloudformation/). As it relates to this issue, the new page describes Karpenter permissions associated with SQS queues. I'm going to close this issue, but feel free to reopen it if there is more that you would like to see in this area.

**Comment by chrisxaustin** [comment]
The [EKS Best Practices Guide](https://aws.github.io/aws-eks-best-practices/karpenter/#enable-interruption-handling-when-using-spot) could use a link to the required permissions for SQS.

Same for the [Migrating from CAS](https://karpenter.sh/docs/getting-started/migrating-from-cas/#create-iam-roles) page since it lists most IAM permissions, but nothing for SQS.

I manage everything through Terraform instead of CloudFormation, so I was surprised to find the the Migration page didn't mention SQS.

**Comment by jonathan-innis** [comment]
@chrisxaustin The maintainer team is pretty swamped with requests (which is obviously a good problem to have 😄 ). Would you be interested in opening a PR to propose the relevant changes to both sets of these docs? The EKS best practice guide changes would go here: https://github.com/aws/aws-eks-best-practices.

At the minimum, if you opened an issue on GH under documentation, that would help us keep track of this request since this issue has been closed.

**Comment by SebastianScherer88** [comment]
@elitistphoenix and others in this thread: as @tgmatt mentioned, the terraform code in the [official aws karpenter module ](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/karpenter) as well as [the official eks karpenter example](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/karpenter) are great resources to convert the official karpenter docs setup into terraform code.

specifically, if you dig into the aws eks karpenter module, you will find the references to sqs resources, events and policies that the karpenter controller pod needs to access from within kubernetes.

**Comment by paul-civitas** [comment]
> Are you looking for more explicit callouts that this CloudFormation template is creating the queue for eventing?

Yes. A cloudformation template is no substitute for documentation for how something is architected. You need to talk about the fact that karpenter needs a queue and why it needs a queue.

**Comment by paul-civitas** [comment]
Currently there are things that allude to an interruption queue, but no where in the docs does it say "this is what the karpenter interruption queue does, this is why it's needed, this is how you should add it if you're migrating from a previous version of karpenter that didn't have an interruption queue. This is why we decided to add it.
