### ISSUE TITLE
maxPods setting ignores instance capabilities

### ISSUE THREAD

**Issue by thomaschaaf** [aws/karpenter#3903]
### Version

__Karpenter Version:__ v0.27.3

__Kubernetes Version:__ v1.26.4

### Expected Behavior

Setting `spec.kubeletConfiguration.maxPods` to 110 caused nodes to think they could handle 110 pods even if the node could not get as many nics/ips. If the ec2 instance can support 58 pods (https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt) and the maxPods config is set to 110 I would expect the node to never try and run more than 58 pods.

### Actual Behavior

The node runs into issues that it can not assign an ip to the nodes and the pods are stuck in pending.

### Steps to Reproduce the Problem

Setting `spec.kubeletConfiguration.maxPods` to 110 and run a small instance like t3.medium and try to run more than 17 pods it will try to schedule them but they will be stuck in pending forever.

### Resource Specs and Logs

```apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: on-demand
spec:
  consolidation:
    enabled: false
  kubeletConfiguration:
    maxPods: 110
  ttlSecondsUntilExpired: 604800
  providerRef:
    name: default
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
  weight: 10
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
It's not always the case that maxPods is limited by the number of IP addresses that can be allocated to a node. For example, if you are using VPC Prefix Delegation for IP address allocation you should be able to consume more IP addresses on the  t3.medium. 

t3.medium w/o prefix delegation: 
 (3 ENIs * 6 IP allocations per ENI * 1 IP allocation) -1 for the host interface => 17 
t3.medium w/ prefix delegation: 
  (3 ENIs * 6 IP allocations per ENI * /28 prefix allocations) -1 for the host interface => 287

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-prefix-eni.html

So there's not a blanket solution to this problem. In general, maxPods shouldn't be the limiting factor for how many pods a node can fit. Resource requests for CPU and memory are usually hit first unless the pods you're scheduling are tiny.

**Comment by bwagner5** [comment]
Let us know if you think we should do something different here, closing for now.

**Comment by anarsen** [comment]
I'm in a similar situation as @thomaschaaf.

Increasing the pod density puts us closer to e.g. registry pull QPS as well, and thus staying within the [Kubernetes thresholds](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md#kubernetes-scalability-thresholds) is generally something we'd really like.

We have a high Pod churn and Pod creation bursts due to the nature of our workloads, so kubelet & friends are really at work on nodes with high pod density.

I would really love a way to define a _ceiling_ of max pods per node 🙏

**Comment by dlemfh** [comment]
> Setting spec.kubeletConfiguration.maxPods to 110 caused nodes to think they could handle 110 pods even if the node could not get as many nics/ips. If the ec2 instance can support 58 pods ([awslabs/amazon-eks-ami@master/files/eni-max-pods.txt](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt)) and the maxPods config is set to 110 I would expect the node to never try and run more than 58 pods.

In order to achieve this, Karpenter could have been implemented this way:
1. first take the "karpenter-calculated" max pod count (=58)
2. and take the "user-inputted" max pod count (=110)
3. finally, set the **min** of the two as the final `maxPods` kubelet config value

But then, some users may want to use the user-inputted max pods value to override the decision (as is the current behavior), because of some flaw in karpenter's automated calculations.

**Therefore, I think karpenter should have a flag to decide between:**
- using the "user-inputted" max pod count to **override** the final kubelet config value (= the current ASIS behavior)
- or using the **minimum** of "user-inputted" and "karpenter-calculated" max pod counts as the final kubelet config value (= what will satisfy the Issue Author)
