### ISSUE TITLE
docs: url contains version causing documentation breaks

### ISSUE THREAD

**Issue by danielhelfand** [aws/karpenter#4007]
### Is an existing page relevant?

Yes

### What karpenter features are relevant?

Not applicable

### How should the docs be improved?

I have been trying to link to documentation around Karpenter in design docs I am authoring, but I find I very frequently need to update links because only some versions are supported in Karpenter docs. Basically, because the url contains the version, the link is broken pretty frequently. Example: https://karpenter.sh/v0.27.3/concepts/scheduling/#well-known-labels

Can you add a `latest` version tag that always contains stable information about Karpenter? Is there a way to do this currently? Thanks!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
I have a PR out that should help with this: https://github.com/aws/karpenter/pull/4001

It will move to major-minor version docs links so that the links are valid for a longer period of time. We actually do have a "latest" path link for docs but it's awkward to find because it's a redirect. The PR linked above also removes that redirect and create a static "latest" path. 

I put "latest" in quotes above because we followed the upstream K8s convention of using /docs/ instead of latest. 

For example, you can go here: https://karpenter.sh/docs and will be redirected to the latest version. If you replace the version in the URL with `/docs/` (i..e `s/v0.27.5/docs/`) , you'll go to latest for that page.

**Comment by bwagner5** [comment]
karpenter.sh will still be the landing page, but after the #4001 is merged, clicking the "Get Started" button or "Docs" in the top right header, will take you to /docs which should make linking to stable URLs easier.

**Comment by danielhelfand** [comment]
Thanks, makes sense. I will close this out then.
