### ISSUE TITLE
provisioner support global cost limit or spot discount limit

### ISSUE THREAD

**Issue by lzjqsdd** [aws/karpenter#4024]
### Tell us about your request

provisioner support also cost limit, not only resource limit.   if some spot instances discount price exceed limit,  or  total cost exceed at global level,  do not privisoning it.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

The price of spot instances always changes with time. Usually, we set the priority of cheap instances higher based on experience,  but there is no guarantee that such a strategy will always be effective. This will be beyond our control when some instance price increase unexpectedly.  We hope to strictly limit the cost of certain Provisioners. For example, when the discount of some instances is higher than 50%, it will not be considered, or the total cost of Provisioner exceeds our expected limit, and it will not be considered.

### Are you currently working around this issue?

We constantly monitor the price of the instance and manually change the provisioner strategy

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Hey @lzjqsdd, thanks for the request. By "discount of some instances is higher than 50%", are you referring to the difference in price of the spot instance and it's on-demand counterpart? Or is there some other discounting mechanism within AWS that you're referring to, like savings plans or reserve instances? 

In all, if you're looking for a global cost limit, https://github.com/aws/karpenter/issues/3244 should cover your use-case.

**Comment by laurent-chriqui** [comment]
Hello, it would be nice for spot instances indeed to have Karpenter take the instant spot prices into account when provisionning within the constraints of a provisionner and try to provision the cheapest node available on the market. It could be an option to activate for a provisioner to take instant prices into account when prioritizing machines. Also sometimes a zone can be cheaper than the others and if the zone does not matter, it would be nice to get the cheapeast machine available.

This would also benefit to the Cloud Providers since a lower price should mean a lower demand and would therefore help balance the spot market.

**Comment by tzneal** [comment]
>  it would be nice for spot instances indeed to have Karpenter take the instant spot prices into account when provisionning w
