### ISSUE TITLE
Karpenter autoscaling eks

### ISSUE THREAD

**Issue by bharathnadigoti** [aws/karpenter#4041]
### Version

v0.26.1

### Expected Behavior

Karpenter to spin up the instances equally in all availability zones. 

### Actual Behavior

Rather it picks random availability zone for provisioning new nodes.

### Steps to Reproduce the Problem

`- key: topology.kubernetes.io/zone
      operator: In
      values: ["us-east-2a", "us-east-2b", "us-east-2c"]`

### Resource Specs and Logs

2023-06-14T17:52:09.592Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "982c35f", "provisioner": "default", "id": "i-00d64db7637459d60", "hostname": "ip-10-142-163-47.us-east-2.compute.internal", "instance-type": "t3.large", "zone": "us-east-2c", "capacity-type": "on-demand"}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
If you'd like to enforce topology spread on your workloads, you should use https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/ to drive this. Karpenter will respect what your workload requirements are and spin up nodes that reflect that. Otherwise, they will spin up nodes in the availability zones that match the allocation strategy that Karpenter uses. 

I'll close this as I believe this should be answered. Feel free to re-open if you disagree!

**Comment by bharathnadigoti** [comment]
@njtran can you help with balanced nodes scheduled across all Availability zones?

**Comment by njtran** [comment]
Sure. You should use some of the constraints listed [here](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#topologyspreadconstraints-field). Max Skew might be good for you to try out. Otherwise, you can ask in the [kubernetes/karpenter slack channel](https://kubernetes.slack.com/archives/C02SFFZSA2K) for more
