### ISSUE TITLE
Metrics Port in the Helm Chart does not match Documentation

### ISSUE THREAD

**Issue by snorlaX-sleeps** [aws/karpenter#4066]
### Version

__Karpenter Version:__ v0.28.0

__Kubernetes Version:__ v1.25 - v.127

### Expected Behavior

The documentation states that the default port for metrics is "8080" which is what we are scraping (documented [here](https://karpenter.sh/v0.28/concepts/settings/))
This should be the port exposing metrics

### Actual Behavior

The default value in the Helm Chart is set to port 8000 [here](https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml#L146)

This is also visible on the pod in cluster:
```
Ports: 8000/TCP, 8081/TCP, 8443/TCP
.....
Environment:
  KUBERNETES_MIN_VERSION: 1.19.0-0
  KARPENTER_SERVICE:             karpenter
  WEBHOOK_PORT:                     8443
  METRICS_PORT:                        8000 
  HEALTH_PROBE_PORT:            8081 
```

This is obviously on the pod / deployment, whereas the docs mention the service. However our metrics provider (Datadog) scrapes the pod, not the service.
The docs should probably state that these ports are different, or they should be related

Port is [hardcoded](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/service.yaml#L16) on the service, but is [dynamic](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/deployment.yaml#L76) on the [deployment](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/deployment.yaml#LL98C29-L98C29)

### Steps to Reproduce the Problem

Deploy the Helm Chart without setting the value explicitly

### Resource Specs and Logs

The logs basically state that the URL is unavailable at that port / url `http://<pod-ip>:8080/metrics`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by snorlaX-sleeps** [comment]
I tired to change the port in the Helm Chart values file to `8080` but that resulted in some interesting errors appearing in the logs and Karpenter refusing to start

**Comment by njtran** [comment]
Hey, sorry about this. We actually changed the port in https://github.com/aws/karpenter/pull/3879. 

Fortunately, the Karpenter [Service refers to the correct port by name](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/service.yaml#L17), but not by number. This means it still works if you scrape the Karpenter pod at port 8000. If you use the [default helm values](https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml#L146), you should see this port as the one that's being used by Karpenter. 

We do have some things to fix in the Karpenter docs and [our defaulting logic](https://github.com/aws/karpenter-core/blob/main/pkg/operator/options/options.go#L52). 

I'll make those changes so that they're reflected, and we'll modify the service to be changed to 8000 to match this in the next release. We're going to include some e2etests to make sure we catch any sort of port incompatibilities like this in the future.

**Comment by snorlaX-sleeps** [comment]
Thanks for the replay @njtran 
Yea, the easy fix for us was to change the port we were scraping, but it took a bit of investigation around missing metrics.
However I later found Datadog can also scrape service endpoints, using annotations.
A possible fix for this would be to allow setting "specific" service annotations, in the same way [podAnnotations](https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml#L43) can be set through the Helm Chart and applied only to the Karpenter pods. Currently services can only use the generic [additionalAnnotations](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/service.yaml#LL8C20-L8C41) and this would benefit from allowing specific KV pairs being set.

> and we'll modify the service to be changed to 8000 to match this in the next release
There's no need to modify the existing setup, as long as the docs mention that the service and pod ports are different.
As I said before I saw some very interesting and new errors by changing the pod metrics port to `8080` using the Helm Chart.
