### ISSUE TITLE
Allow to configure more storage for the provisioned nodes

### ISSUE THREAD

**Issue by gdevelek** [aws/karpenter#4149]
### Description

My pods are getting evicted due to node pressure (for ephemeral storage) on a node that houses about 100 pods. The node has 20GB of space by default, and it appears there's no way to increase that. Running v0.26.0 on K8s v1.24

**Comment by jonathan-innis** [comment]
Yes, [`blockDeviceMappings`](https://karpenter.sh/docs/concepts/node-templates/#specblockdevicemappings) is the de-facto way to increase your static storage with Karpenter. There's also [this open issue](https://github.com/aws/karpenter/issues/2394) that is covering dynamically scaling ephemeral storage based on pod requests. This issue is on our roadmap so it will be coming out with Karpenter at some point in the future.

**Comment by pkit** [comment]
@jonathan-innis my god, guys, did you ever test it? why I'm coming to full-stop issues every day?
I have huge images, that need shitload of ephemeral storage, why I need to live with 20GB?
Each image is 4-5GB, it's python. So, only 5 pods per node on  sunny day??

**Comment by MykolaDzhamQC** [comment]
> @jonathan-innis my god, guys, did you ever test it? why I'm coming to full-stop issues every day? I have huge images, that need shitload of ephemeral storage, why I need to live with 20GB? Each image is 4-5GB, it's python. So, only 5 pods per node on sunny day?? And adding EBS volume to store images is...strange, no?

You probably need to just read the documentation for `blockDeviceMappings` and add it to the `EC2NodeClass`. Yes it works
