### ISSUE TITLE
Script files paths are invalid

### ISSUE THREAD

**Issue by mbevc1** [aws/karpenter#4319]
### Description

**How can the docs be improved?**
Current docs in the Getting started section are not using correct paths for script files and links are broken, i.e. Grafana config: https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#add-optional-monitoring-with-grafana

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Thanks for pointing this out. We changed up the docs versioning scheme for v0.28+, which those commands check out what the repo looked like at that tag. This should eventually be phased out when we release more versions, but in the meantime, I'll hard-code the fix to those links so that they're correct.
