### ISSUE TITLE
Provisioner Capability: Prioritize on-demand with opportunity to request "Spot"

### ISSUE THREAD

**Issue by kevarr-vg** [aws/karpenter#4402]
### Description

**What problem are you trying to solve?**

Currently, Karpenter prioritizes Spot offerings if the provisioner allows Spot and on-demand instances

```yaml
  requirements:
  - key: "karpenter.sh/capacity-type"
    operator: In
    values: [ "spot", "on-demand"]
```

I would like to request that there be some capability to flip this ordering: Prioritize on-demand instances, but allow workloads to prioritizes Spot offerings if requested (e.g. with `nodeSelector`).

I know the API is already capable of handling this. I could create two weighted Provisioners, one that allows on-demand and another that prioritizes spot, and use something like a `nodeSelector`/`tains/tolerations` to use the "Spot" provisioner for certain workloads. But it would be nice if I didn't have to essentially duplicate my provisioner in order to achieve this.

**How important is this feature to you?**

This feature would reduce the number of provisioners I maintain in my cluster.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Personally, I'm not in-favor of making this configurable on which one to prioritize. I can understand the use-case, but I can also see more issues popping up where everyone has different configurations which makes examples harder to consume (for example, if we said the yaml values were ordered for capacity-type). Ordered values I think would be awkward no matter what in values.  The other way would be a separate configuration. 

We've really tried to limit the configuration to make Karpenter easier to use and only expose configuration if it's absolutely required. Since there is another way to accomplish prioritizing OD over Spot, we'd rather not expose an ad-hoc config for it.

**Comment by njtran** [comment]
I'm on the same page as @bwagner5. We prioritize spot when both are defined because spot is strictly cheaper than on-demand. If you are able to set pods to request spot with a node selector, you can do the inverse and allow pods to select on-demand currently. In addition to the weights approach, there seems to be a good path forward for you, even if you have to duplicate your Provisioners. I'm going to close this, but feel free to cut another issue if you feel that you have a prioritization need that isn't properly reflected with Karpenter's current behavior.
