### ISSUE TITLE
Unable to delete instances using recommended IAM policy

### ISSUE THREAD

**Issue by johngmyers** [aws/karpenter#4527]
### Description

**Observed Behavior**:

ERROR	controller	Reconciler error	{"commit": "f78c0d9-dirty", "controller": "termination", "controllerGroup": "", "controllerKind": "Node", "Node": {"name":"i-0a7eaf2e0e3c0690d.ec2.internal"}, "namespace": "", "name": "i-0a7eaf2e0e3c0690d.ec2.internal", "reconcileID": "ff349b6d-5c23-449f-b5b9-d59594563b92", "error": "terminating cloudprovider instance, terminating instance, UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: 6g8KJmcoYD09gfnd_7Xco-LcBTliC2Q8W6getENsc2hAB9MNlhaWO80r9uqTgIQhPxc8vEHUp9JFFZ7INFgHe98pMNoqNIk-ZUDHsgvOppx909z3hE923cq5Y6vYr6ml2BxTeZdbLC-86_Ebnve7pi6gsYRv4C2Q9pmudFG8r-J1TjQvIT2Gi-SWNI842R3Us9nKCy0KlB_PU-wFLdSdPf97r8V8NwU7yUVqx65vr_FvhpBv358SWjsv7er_nSOpWYpXVzyiOfSyW317hpTG1LgJ2n6_p064bfjLiXJwZcHEpIl1_Dbb7hve_fBxSo7LOdqzcNM49aBvOQ9bCJM0bqqObaNWjoZnT8SAzMJfFRXbnd7Fb5spVXmVi_g744PLdBdIiIUNHHIfkRHrYIwN4vCCAtAPf4BNDlnk9OqbXp6yaki8hvdVWbNL1sBBS6mydTT7GT3QGliBvEDWSgvE_qeO6F85nAgoUyLU1ALN-aFHkpTwIAyz6-HIF5aw7Sh3sKgnSmNrPsriGz4Bv7wtQkVXZng9TKGxRgwS6LW4M206SUBgh1SJKk_m-_9la6xBNSmICwPEc5wxDKGxiUKQ4dYEqwKOLVBpMYiC6h2tkyt5FPW8UCC2nhYF7HMBOzqgSq_tRrbdgp1c9MwyKLgul9i7vrcGBZL7orw6BaPdd4o8xU8evIc39NZzFSxYqM5EIHzuI-M7eoq-WUpBQlL7MLOikTWqf1gzBYk9OhqeNalCT1shh7IE-ctaXJFk0PpUUbL5ynB4mJbgPkWF5RJpyowTYnCzM2tg22bDLTCrhMzu81IvFjkr_lIjmAPPztHcJIj8SP6WcyCe94tXuilwZMYJ2CejEFZgujFOXPBuYUE99s_-xYIi8A0ah890woMLnmo2SSA81XPMTcyP05iGL8pkbqop2-R8llI-vbVVkpIBxq3fegZpR6yEXudacKOPHYX8fFPr2_RQi05UWhyD2myF58aFnl8jYlhK-0oApI_t_4PXskJV7SJXe1JdS9j6gnDhKjlWILlbsqye5Ey4qwRMA00ro_3nnp2S1yZCtGBM7ePWbZpbrrxR80bDQ4cizvoaPAS51ihw-KgGoPslkHNNmJfylRUO8X0ullaYCGXyKwBm5exDxH3xs684ORM0Xsm3CfY67eSkvMO8z9H9gl1gviQX_RB0xpQqlSY1f3VIOYXSlx6K6yAsW7Eai19EbQ2Knyw6rqN2QXQysZFhMhj7amVHcexARnEzU5sd-W6GAtT4ZkiKObYRni9MiioEHbZbNp-lRllbkv8uSUZWLmbHLNKF\n\tstatus code: 403, request id: 7cfbcbb2-ee47-4ada-acf2-75ec98250147"}

Looking at the decoded message, I see no condition items with key `aws:ResourceTag/karpenter.sh/provisioner-name`, etc. I do see condition items with key `ec2:ResourceTag/karpenter.sh/provisioner-name` 

**Expected Behavior**:

Successful termination

**Reproduction Steps** (Please include YAML):

* Use controller IAM policy derived from https://github.com/aws/karpenter/blob/main/website/content/en/v0.29/getting-started/getting-started-with-karpenter/cloudformation.yaml (but using a different cluster ownership tag)

* Delete a provisioned node

**Versions**:
- Chart Version: 0.29.0
- Kubernetes Version (`kubectl version`): Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532"

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Are your instances tagged with the `karpenter.sh/provisioner-name` tag?

**Comment by johngmyers** [comment]
Yes, one of the condition items in the decode message is:

```
        {
          "key": "ec2:ResourceTag/karpenter.sh/provisioner-name",
          "values": {
            "items": [
              {
                "value": "default-arm"
              }
            ]
          }
        },
```

However, there is no condition item with a key of `aws:ResourceTag/karpenter.sh/provisioner-name`.

**Comment by jonathan-innis** [comment]
Do you know why your instances don't have the `karpenter.sh/provisioner-name` tags? We use these tags as a security boundary to determine which instances that Karpenter owns so we don't want to be able to delete instances in EC2 that:
1. Are not owned by _this_ cluster (`kubernetes.io/cluster/<cluster-name>`)
2. Are not owned by Karpenter (`karpenter.sh/provisioner-name`)

**Comment by johngmyers** [comment]
My instances do have the `karpenter.sh/provisioner-name` tags

**Comment by johngmyers** [comment]
I might be seeing propagation delay on IAM policy changes.

**Comment by johngmyers** [comment]
This isn't reproducing anymore. Must have been propagation delay.

**Comment by xsvil** [comment]
I am facing the same issue as here but with version 0.32.1. More specifically I am using nodeclass and nodepool.

I am following the updated documentation from: [getting-started/migrating-from-cluster-autoscaler](https://karpenter.sh/docs/getting-started/migrating-from-cas/#create-iam-roles ) and the controller policy i set doesn't seem to be able to terminate instances. Old policy before introducing nodepools and nodeclasses used to work.

The received error message is quite generic:
`terminating cloudprovider instance, terminating instance, UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::<accountId>:assumed-role/karpenter-controller-role-ops/<session> is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:<region>:<accountId>:instance/i-<instanceId> because no identity-based policy allows the ec2:TerminateInstances action. Encoded authorization failure message`

I have even tried changing the block to get anything related to *karpenter* but it still doesn't work:

`{
            "Action": "ec2:TerminateInstances",
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/*karpenter*": "*"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "ConditionalEC2Termination"
        },`

I have also noticed from the decoded message that the condition karpenter wants to meet are referring to the accountId in some occasions:

> "<accountId>:aws:ec2launchtemplate:version"
"ec2:ResourceTag/aws:eks:cluster-name"
"ec2:MetadataHttpPutResponseHopLimit"
"ec2:ResourceTag/aws:ec2launchtemplate:version"
"ec2:InstanceMarketType"
"<accountId>:karpenter.sh/nodepool"
"aws:Account"
"ec2:ResourceTag/karpenter.k8s.aws/ec2nodeclass"
"ec2:AvailabilityZone"
"ec2:ResourceTag/Name"
"ec2:InstanceType"
"aws:Region"
"ec2:InstanceMetadataTags"
"aws:Service"
"<accountId>:aws:ec2launchtemplate:id"
"ec2:MetadataHttpTokens"
"ec2:ResourceTag/karpenter.sh/nodeclaim"
"ec2:ResourceTag/karpenter.sh/nodepool"
"aws:Type"
"ec2:Tenancy"
"<accountId>:aws:eks:cluster-name"
"ec2:ResourceTag/karpenter.sh/managed-by"
"ec2:InstanceAutoRecovery"
"ec2:ResourceTag/aws:ec2launchtemplate:id"
"<accountId>:karpenter.sh/nodeclaim"
"aws:Resource"
"ec2:ebsOptimized"
"<accountId>:karpenter.k8s.aws/ec2nodeclass"
"ec2:RootDeviceType"
"ec2:InstanceProfile"
"<accountId>:karpenter.sh/managed-by"
"ec2:MetadataHttpEndpoint"
"ec2:ResourceTag/aws:ec2:fleet-id"
"<accountId>:Name"
"ec2:InstanceID"
"<accountId>:kubernetes.io/cluster/ops"
"<accountId>:aws:ec2:fleet-id"
"ec2:Region"
"ec2:ResourceTag/kubernetes.io/cluster/ops"
"aws:ARN"

Could we have the updated policy?

[decoded-authorization-message.json](https://github.com/aws/karpenter/files/13322767/decoded-authorization-message.json)
