### ISSUE TITLE
Add support for graceful shutdown options to Provisioner spec

### ISSUE THREAD

**Issue by AlexMaksimkin** [aws/karpenter#4536]
### Description

**What problem are you trying to solve?**
Current Provisioner spec `sh.karpenter.v1alpha5.Provisioner.spec.kubeletConfiguration` are missing support for graceful shutdown kubelet configuration, in particular:
- shutdownGracePeriod
- shutdownGracePeriodCriticalPods
- shutdownGracePeriodByPodPriority

https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-ShutdownGracePeriodByPodPriority

which block any ability to use of graceful termination features with Karpenter.

**How important is this feature to you?**

Many workloads are require graceful shutdown as well as doing that in particular order.
BottlerocketOS recently added related support: https://github.com/bottlerocket-os/bottlerocket/pull/2930, https://github.com/bottlerocket-os/bottlerocket/pull/3308, but Karpenter couldn't use it without additional support in Provisioner specs.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@AlexMaksimkin Can you pass the additional values down to the bootstrapped KubeletConfig by performing overrides similar to what's described in our [upstream docs](https://karpenter.sh/docs/concepts/node-templates/#al2-and-ubuntu:~:text=You%20can%20also%20set%20kubelet%2Dconfig%20properties%20by%20modifying%20the%20kubelet%2Dconfig.json%20file%20before%20the%20EKS%20bootstrap%20script%20starts%20the%20kubelet)?

We've generally been trying to avoid adding _all_ the support KubeletConfiguration fields into the Provisioner (since there's a lot of fields) and tried to scope the fields to just be fields that are related to scheduling behavior that Karpenter should be aware of without having to introspect the userData.

**Comment by bwagner5** [comment]
Looks like we do need to update the Bottlerocket settings configuration to support this, but we shouldn't need to add this to the kubelet configuration in the provisioner spec.

**Comment by bwagner5** [comment]
Added support for graceful shutdown, will be available in the next Karpenter release.
