### ISSUE TITLE
When a pod can't get an ip, it continues to pending, and karpenter can not detect it.

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#4557]
### Description

version: v0.30.0
eks environment: I've used cilium's cni, not aws-cni.

I assigned 128 ip's to each node.  means that each node is allocated up to 126 pods
```
  Ipam:
    Pod CID Rs:
      172.16.10.0/25
```
But i use m6i.2xlarge can support pods:  234

When I start more than 130(>128) pods, the pod keeps on pending, and reports an error(no ip can allocate)
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4d0e21b994a06cec32a644f427eb559da250246b2dced95d2a8adffb493532b6": plugin type="cilium-cni" name="cilium" failed (add): unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure range is full

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9b2c85a0190b75e317f57ac53c2eb5753bddd3e410162824a5a67b9679efe808": plugin type="cilium-cni" name="cilium" failed (add): unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure range is full

```

But karpenter won't sense these pending pods.

1. I want to know why this is
2. i want to know what the karpenter detection mechanism is
Is it based on pod pending to expand nodes.  Or does it look at the number of pods supported by maxpods first?

**Comment by bwagner5** [comment]
Karpenter will default the node to the calculations recommended for the AWS VPC CNI (basically this https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt). If pods get scheduled to a node, but can't obtain an IP address, then Karpenter can't do much about it since if Karpenter evicted the pod, kube-scheduler could make the same scheduling decision since the node appears to have slots available. 

If you set maxPods on your provisioner, kube-scheduler will know how many pods can fit on a node based on your /25 allocation.  https://karpenter.sh/docs/concepts/provisioners/#speckubeletconfiguration

**Comment by txjjjjj** [comment]
@bwagner5 So for my case I should specify that the maxPods pods is less than or equal to the number of supported ips

**Comment by bwagner5** [comment]
> @bwagner5 So for my case I should specify that the maxPods pods is less than or equal to the number of supported ips

Yes, that is correct

**Comment by bwagner5** [comment]
Feel free to reopen if you have further issues!
