### ISSUE TITLE
Add tutorials section 

### ISSUE THREAD

**Issue by sadath-12** [aws/karpenter#4866]
### Description

**How can the docs be improved?**

Right now we have ```getting-started``` guide and ```concepts``` section to get familiar with the project for end users but it would be more fruitful if they can understand to what potential our project could be extended.

We can do this by adding tutorials section where we can cover some uncommonly used parameters and put out the stylish (ofcourse for the better ) usecases of it.

By this way maybe we can make our project more adaptable and lovable

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Was there a specific tutorial you were thinking that would be useful here? 

Since there's such a large dimensionality of use-cases in Kubernetes, we've found it better to host some examples of Karpenter CRDs in https://github.com/aws/karpenter/tree/main/examples and let users pick which features in the `concepts` section seem interesting to their use-case. 

It might be cool to have a Drift tutorial, but that would be identical to the getting-started guide with one extra `kubectl edit provisioner` call at the end.

**Comment by sadath-12** [comment]
Ya there are good examples and often work as good templates for the users to use them directly and modifying for their usecase . I just thought like if we can have a tutorials section where we describe a scenario and show how exactly to leverage certain features of karpenter

**Comment by ellistarn** [comment]
Hey @sadath-12. We have limited resources to maintain our documentation, and try to keep it as focused an accurate as possible. The more content we add, the harder it is to maintain. We recommend folks write blog posts for this kind of content, rather than adding to the maintainership burden.
