### ISSUE TITLE
[Feature] Gracefully roll workloads with only 1 replica

### ISSUE THREAD

**Issue by mattparkes** [aws/karpenter#500]
**Tell us about your request**
We have a few Pods in our system which we can only run 1 of (and that we preferably don't want to be running `0` of).

Depending on how you implement #452, when a Node is Terminated and gracefully drained, etc, presumably the Controller will just Delete all the Pods and let Kubernetes schedule replacements, or, if it would violate the PDB, do nothing. Rather than just deleting these, it would be nice if there was an option to instead do a `rollout restart` so that a new pod is brought up (and becomes Ready) before the old one is Terminated.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The impact of not doing it this way is an interruption to our Pods which are `replicas: 1`. Of course the _real_ fix is to solve that, but that is not always possible e.g tech-debt, licensing, etc.

**Are you currently working around this issue?**
We currently use `cluster-autoscaler`, `node-termination-handler` and our own custom controller (written with `kubebuilder`) to detect the Taints being added by `node-termination-handler` and then we `rollout restart` any Pods which are single replicas and have a PDB.

**Additional context**
We don't currently use Karpenter, we're holding off until a few features we need land in/around `0.3`, but we wanted to flag this as a use-case.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Taking a look through https://github.com/kubernetes/kubectl/blob/652881798563c00c1895ded6ced819030bfaa4d7/pkg/cmd/rollout/rollout_restart.go#L134, I think we could support this by checking owner reference of pods, and then patching in a change to the corresponding statefulset, daemonset, or deployment after cordoning the node. Instead of evicting the pods ourselves, we could simply rely on the controller to execute the rollout to gracefully ensure uptime of the pods.

This is a great suggestion and I totally see the value here. @njtran, do you think you can scope this into #452?

**Comment by mattparkes** [comment]
Yeah that's exactly how we do it. We check the owner and then update `spec.template.metadata` with a `restarted-at` annotation (rather than pulling in `kubectl` `rollout`).

**Comment by mattparkes** [comment]
Alternatively if you can't or don't want to handle this logic directly in `karpenter`, all we need is an event we can subscribe to so that we can do this ourselves.

The current Taint based approach of `node-termination-handler` is perfectly suitable, since we can `watch` for that, but we're happy to adapt to whatever you come up with (e.g webhook, etc).

**Comment by ellistarn** [comment]
> Alternatively if you can't or don't want to handle this logic directly in karpenter
I think we should handle this.

> all we need is an event we can subscribe to so that we can do this ourselves.
I'm trying to think about potential extension points. Right now, you could potentially annotate pods with do-not-evict and then handle the drain yourself when a node.metadata.deletionTimestamp is set. It strikes me that it might be a bit annoying for you to label every single pod with `do-no-evict` to achieve this behavior. I wonder if it would make sense to support an additional node label (or annotation?) of `do-not-evict`, and we would simply rely on a third party to do the eviction.

**Comment by ellistarn** [comment]
Thinking a little further on this, I'd probably want to constrain this behavior in some way. It would be surprising to trigger a full rollout to any deployment that happens to have a pod on a terminating node, and also rollout all the pods on happily running nodes. 

I could see doing this with a pod annotation `rollout-on-evict`, or potentially constraining this behavior to only execute if the deployment/statefulset/daemonset has one replica. This makes less sense in the daemonset case, since you'll likely have many of these that won't need the rollout.

**Comment by ellistarn** [comment]
Another approach is to use termination grace period. When the evict is triggered, you could use a combination of PreStop[https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks] and TerminationGracePeriod to clean up, but this won't allow new connections to be made, since the Endpoint resources will be removed as soon as eviction is triggered.

**Comment by ellistarn** [comment]
Also -- can you describe the case where this is useful for daemonsets? I can see deployments/statefulsets with 1 replica.

**Comment by mattparkes** [comment]
It's definitely not useful for DaemonSets, nor is it really useful for anything with more than `1` replica, since as you said, you don't want everything rolling because 1 Node got terminated (and in the case of multiple Nodes terminating at once, you'll end up with multiple PATCH/PUTs which can get a bit jank).

Unfortunately we haven't open-sourced the code for our Controller (yet), otherwise I'd just link that so you can see the logic. But we only handle Deployments with `replicas: 1` _and_ when there's a matching PodDisruptionBudget (since otherwise it's a race with the `node-termination-handler` draining the Node and deleting the Pod anyway).

The annotation `rollout-on-evict` would be useful. We haven't implemented such logic since _all_ our `replicas: 1` Deployments benefit from being handled this way, but adding that annotation to our Deployments which require this functionality wouldn't be a problem for us (and I can see cases where people very explicitly don't want this to happen).

**Comment by mattparkes** [comment]
Although I think you understand it, for clarification the sequence of events in our current configuration is this:

 1. `cluster-autoscaler` or a user starts a scale down
 2. `node-termination-handler` receives the termination event
 3. `node-termination-handler` cordons the node (adds the cordon taint)
 4. `node-termination-handler` taints the node
  > If true, nodes will be tainted when an interruption event occurs. Currently used taint keys are `aws-node-termination-handler/scheduled-maintenance`, `aws-node-termination-handler/spot-itn`, `aws-node-termination-handler/asg-lifecycle-termination` and `aws-node-termination-handler/rebalance-recommendation`

 5. _Simultaneously:_
 5a. `node-termination-handler` starts deleting Pods (but any `replicas: 1` pods with a `PodDisruptionBudget` cannot be deleted since it would violate the PDB and so `node-termination-handler` complains about these in its logs)
 5b. our `node-evacuator` controller (which was `watching` for changes to the Nodes objects) sees one of the `aws-node-termination-handler` taints added to the Node and does a `rollout restart` (via adding a `restarted-at` label) of any `replicas: 1` Pods with a matching PDB.

 6. The Node is eventually empty (either from `node-termination-handler` deleting Pods or our Controller PATCHing their owner and causing a rollout restart and the Node is `deleted` and the Instance is `Terminated`

**Comment by mattparkes** [comment]
To further complicate (or maybe reduce the complexity of) this, Kubernetes has built in Graceful Termination now: https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/

**Comment by ellistarn** [comment]
Hey @mattparkes , I think that this is probably in the purview of another tool in the ecosystem. It should be straightforward to implement a custom controller that integrates w/ karpenter's termination workflows.

**Comment by mattparkes** [comment]
Yeah we can totally do that. As I said in my initial post, that's currently how we do it:

> **Are you currently working around this issue?**
We currently use cluster-autoscaler, node-termination-handler and our own custom controller (written with kubebuilder) to detect the Taints being added by node-termination-handler and then we rollout restart any Pods which are single replicas and have a PDB.

However I do think that is definitely outside the reach of a lot of Amazon's customers, so it would be awesome if that was something you could provide at some point in the future, either as another tool or as a "plugin" for `karpenter`.

Can you give me any suggestions for the most suitable event that we should use to ascertain that karpenter is starting to terminate the Node? We currently use the taints added by `node-terminationa-handler` but skimming the code I don't see something similar in Karpenter?

**Comment by ellistarn** [comment]
For karpenter, `node.deletionTimestamp` will be set once karpenter starts to finalize the node.

**Comment by JulesLalu** [comment]
Hello,

Two years later, I would like to know what's the most straight-forward way for achieving such a rollout in Karpenter's current version (0.29). Were some features implemented, that enable graceful rollout of deployments with 1 replica, e.g during consolidation or Spot Interruption ?

Thanks in advance for your help !

**Comment by Frodox** [comment]
Hi @mattparkes @ellistarn 

I have a similar situation where I have an application with a single replica and I can't perform rebalancing without downtime. 

Could you share maybe the most up-to-date solution for the issue? Like share your custom contoller or any other examples?

**Comment by marc-ostrow** [comment]
@Frodox I followed @ellistarn's advice https://github.com/aws/karpenter-provider-aws/issues/500#issuecomment-993009615 and wrote a custom controller using Kubebuilder.  My initial solution, albeit clunky, works, but could have probably been done better.  It also was my first attempt with using Kubebuilder, or any similar framework; albeit I did have some client-go experience).

To get this to work, single replica deployments would require an associated blocking (minAvailable = 1, or maxUnavailable = 0) PodDisruptionBudget to be deployed, and a Nodepool having a terminationGracePeriod specified, I used 48h.

My NodeReconciler is constructed with a copy of the manager's Config (*rest.Config), and a command line parameter value for eviction delay which defaults to 30s (will get back to this).

When the controller is setup, I use a predicate that only returns true for updates to nodes labeled with "karpenter.sh/nodepool" and where the node's DeletionTimestamp transitions from its zero value to a non-zero value -- when the APIServer sets the node's DeletionTimestamp.

So as per the [documentation](https://karpenter.sh/v1.0/concepts/disruption/#control-flow), when a Karpenter node is deleted, the finalizer will block node deletion, yet the APIServer will set the DeletionTimestamp and Karpenter's node termination controller takes over, taints the node, then uses the K8s Eviction API to evict Pods as documented.

My simple solution is to wait an arbitrary, configurable, period of time (defaults to 30s), to allow Karpenter to evict all the Pods it's going to evict.  After this configurable period of time, the Pods left, that we care about, are PDB blocked Pods, but there could also be Pods remaining that are protected by a PDB limiting the disruption rate.

Using the NodeReconciler's config, the Reconcile function creates a clientset, and

- gets the list of Pods on this node, then for any Pod that is owned by an apps/v1 ReplicaSet having replicas set to 1, that is owned by an apps/v1 Deployment.  The Pods' namespace and ReplicaSet owner's name are marked down.
- for any deployment information marked down, these deployments are strategically-merged patched, adding/updating a PodTemplateSpec annotation that causing the rollout restart.

Each updated deployment goes through it's rollout restart and gracefully terminates the old replica on the node.  Once all such Pods on the node have exited, the node termination controller continues to reclaim the node.

**Comment by Frodox** [comment]
@marc-ostrow thank you very much for the detailed answer!


Could you explain why you used a custom controller instead of an operator? What is the difference for this task?

I didn't quite catch the moment - does Karpenter's Termination Controller and your "NodeReconciler" run simultaneously? Or how is it ensured that NodeReconciler runs before/after/during Karpenter's Termination Controller?

> To get this to work, single replica deployments would require an associated blocking (minAvailable = 1, or maxUnavailable = 0) PodDisruptionBudget to be deployed

We are talking about the situation where replicas: 1, right? But if we set pdb.minAvailable=1 / maxUnavailable=0, then the pod's pdb.status.disruptionsAllowed = 0 and Karpenter won't even start consolidation on this node with an error.

> DisruptionBlocked node/ip-... Cannot disrupt Node: PDB "app-ns/app-pdb" prevents pod evictions

I also saw this in the documentation https://github.com/aws/karpenter-provider-aws/blob/main/designs/consolidation.md#pods-that-prevent-consolidation

I don't understand how consolidation starts for you. How did you manage to do this?

**Comment by marc-ostrow** [comment]
@Frodox 

> Could you explain why you used a custom controller instead of an operator? What is the difference for this task?

It's my understanding that an operator defines at least one CRD and one or more controllers, whereas I just needed to watch v1/Node's for their DeletionTimestamp being set.  I had run kubebuilder init specifying a company domain, a project name, and provided my gitlab repo name.  Then when I went to create the api with kubebuilder create api, I specified group core, version v1, and kind Node; and then answered the questions: 1) Create Resource [y/n] with "n" for no, and 2) Create Controller [y/n] with "y" for yes.

> I didn't quite catch the moment - does Karpenter's Termination Controller and your "NodeReconciler" run simultaneously? Or how is it ensured that NodeReconciler runs before/after/during Karpenter's Termination Controller?

The short answer is "yes, independently, and during, by design.  It is assumed that the NodePools' terminationGracePeriod is longer than the time it takes to trigger the rollout-node-controller, for it to make the decision to update/patch the appropriate apps/v1 Deployments, and for possibly new node(s) to be scaled out and become ready, and for the terminationGracePeriods of the Pods terminating due to the rollout restart.   I'm defining my NodePools with a 48 hour terminationGracePeriod so this never would happen.

> We are talking about the situation where replicas: 1, right? But if we set pdb.minAvailable=1 / maxUnavailable=0, then the pod's pdb.status.disruptionsAllowed = 0 and Karpenter won't even start consolidation on this node with an error.

Yes, for me, Pods owned by an apps/v1 ReplicaSet with spec.replicas set to 1, or not defined (?? which should never happen, but who's default value is 1); being owned by an apps/v1 Deployment. **If the NodePool specifies a terminationGracePeriod** (I am using 48h), **then voluntary node disruption (consolidation), does, indeed, take place**, but PDB blocked Pods are not evicted as the Eviction API returns an error indicated that they are PDB blocked.  So the Termination Controller will wait the specified NodePool terminationGracePeriod before forcefully killing the Pods and reclaiming the node.

However, nodes that have pods with a do-not-evict annotation are not considered for consolidation, as per the [Troubleshooting documentation](https://karpenter.sh/docs/troubleshooting/#karpentershdo-not-evict-annotation).

> I also saw this in the documentation https://github.com/aws/karpenter-provider-aws/blob/main/designs/consolidation.md#pods-that-prevent-consolidation

Well, I know blocking PDBs with NodePool terminationGracePeriod set works, as this is how Karpenter 1.0.6 is working today.  I've already mentioned the Troubleshooting section on do-not-evict. And I'm not sure about the last point about not being able to move a Pod due to scheduling constraints...  I'd have to setup a test case, and assuming such a Pod is of a single replica deployment, the rollout-node-controller would perform a rollout-restart, which would cause a similarly specified Pod to be provisioned, and because the node was tainted, Karpenter would be forced to bring up yet another node meeting the Pods' scheduling constraints.  

> I don't understand how consolidation starts for you. How did you manage to do this?

I caused drift in the NodePool requirements: I had had minimum instance size requirements set to 2xlarge when a large instance size would have been more cost effective, then updated the requirements allowing large instance sizes.  I also disrupted the node simply by submitting a delete request for the node.

**Comment by marc-ostrow** [comment]
@Frodox Okay, I'm updating my rollout-node-controller to not use the filter so either on controller restart, or on leader election change, all nodes are looked at and discerned only if it's a karpenter node, and the DeletionTimestamp has a non-zero value.  Also, patching the deployment with an PodTemplateSpec annotation being my custom domain /restartedAt with a value set to the DeletionTimestamp of the node, so the deployment update becomes idempotent.

**Comment by Frodox** [comment]
@marc-ostrow hmm, thank you for sharing your thoughts and insights!

Could you share your code for rollout-node-controller maybe in some way?

**Comment by fclairamb** [comment]
At @stonal-tech, we handled it with a [webhook validation controller](https://github.com/stonal-tech/graceful-drain-controller). A pod eviction around a single-replica deployment triggers a rollout restart of the deployment and is refused until the rollout is finished. It works well...

**Comment by ellistarn** [comment]
**KEP-4563: EvictionRequest API (K8s v1.36 alpha)**

There's a new upstream KEP that's directly relevant here: [KEP-4563: EvictionRequest API](https://github.com/kubernetes/enhancements/issues/4563).

Today, pod eviction is imperative -- the API server deletes the pod immediately and the workload controller races to recreate it. For `replicas: 1` workloads, this guarantees a window of zero availability during node drain.

KEP-4563 introduces a declarative `EvictionRequest` resource and an interceptor mechanism. Instead of deleting the pod outright, a drain orchestrator creates an EvictionRequest. The pod declares an ordered list of interceptors (`.spec.evictionInterceptors`) that get control of the eviction process sequentially. Each interceptor can perform custom logic -- data migration, waiting for computations, or critically, surging a replacement pod -- before signaling completion or terminating the pod. If no interceptor acts within 20 minutes, the eviction request controller falls back to standard API-initiated eviction.

**Important caveat:** The alpha (v1.36) delivers the core API and controller machinery, but native workload-level interceptor support (e.g., Deployment/ReplicaSet automatically surging before evicting) is explicitly a non-goal for alpha and listed as a future improvement. So out of the box, this doesn't solve the single-replica problem yet -- a controller like Karpenter would need to either:
1. Implement its own interceptor that surges a replacement before terminating the original, or
2. Wait for upstream workload controller interceptor support in a later release

That said, this KEP establishes the foundation that makes zero-downtime drain for single-replica workloads achievable without the PDB workarounds and custom controllers described in this issue.

Relevant links:
- KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4563-eviction-request-api/README.md
- API PR: https://github.com/kubernetes/kubernetes/pull/137050
- Controller PR (WIP): https://github.com/kubernetes/kubernetes/pull/137133
