### ISSUE TITLE
Get reasons of nodes termination

### ISSUE THREAD

**Issue by Rez0k** [aws/karpenter#5049]
Hi all,

I want to log the reason that a node is being terminated with karpenter.
for exmaple: if a node got consolidated, or terminated due to spot interupt or by health check I want to know it, so I can track those events and understand why pods on this node terminated.

What is the best approch for this?
Should I use the event bridge with sqs option and log the requests to s3 (or other alternative), does this logs sufficent enough to understand the cause of the node termination?

Or maybe I should forward all of karpenter logs (with fluend for example) to s3 (or other alternative) and filter it later, does the logs karpenter generate are enough to understand the termination cause (spot interrupt, health check etc...)?

any ideas?
maybe karpenter can add this feature, it can be really nice to track down my nodes.

**Comment by Rez0k** [comment]
> The karpenter logs will contain the reason of each node termination. To understand at the cluster scale you also have the option of [karpenter metrics](https://karpenter.sh/docs/reference/metrics/) that are available in Prometheus format. You can see trends of what is causing nodes to be terminated.

Thanks!
I think this is good for me

**Comment by shail-jaiswar24** [comment]
@engedaam Could you please help me out proper that gives info about Node terminated due to Spot Interruption.

We are on karpenter:v0.30.0 have used below metrics:

karpenter_deprovisioning_actions_performed --> "action" don't have anything related to interruption/spot-termination.

karpenter_interruption_actions_performed --> "action" have CordonAndDrain OR NoAction value but nothing wrt interruption and it output matches to above metric "action" output "consolidation/delete".

karpenter_nodes_terminated --> Doesn't have reason for termination.

Am I missing anything here OR spot termination data is available in future version of karpenter

**Comment by jonathan-innis** [comment]
> Am I missing anything here OR spot termination data is available in future version of karpenter

Is the event information that is attached to the Node and NodeClaim sufficient here or do you need Karpenter specifically to surface a metric on node termination reason for a particular node. This gets a tad tricky with a counter when it comes to cardinality since this might increase and get bigger and bigger over the lifetime of Karpenter. Realistically, this counter is probably not going to get _that_ big because node count is probably fairly small over the lifetime of Karpenter but the memory consideration is something to note. 

We could consider culling old counters after some amount of time since you should be using rate for counters anyways.
