### ISSUE TITLE
License Verification Automation (for test code)

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#610]
**Tell us about your request**
We need automatic license verification to avoid issues like https://github.com/awslabs/karpenter/issues/608 when adding new dependencies. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Not all licenses are apache2, and developers can easily make mistakes.

**Are you currently working around this issue?**
Manually

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Automated license verification is performed in our CI for packages that end up in the karpenter executable. However, packages that are used in tests are not checked since they are removed from the executable that is distributed. 

https://github.com/awslabs/karpenter/blob/main/Makefile#L41-L43


I thought `golicense` might just work if we fed it test binaries generated with `go test -c` but it seems to not like those:

```
$ golicense aws.test
⚠️  "aws.test" ⚠️

This executable was compiled without using Go modules or has
zero dependencies. golicense considers this an error (exit code 1).
```

**Comment by ellistarn** [comment]
Oh wow. This is a great clarification.
