### ISSUE TITLE
Add troubleshooting docs

### ISSUE THREAD

**Issue by trondhindenes** [aws/karpenter#647]
**Tell us about your request**
Trying to get Karpenter to work

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm at the point where I've followed the getting started guide, and can see that nodes are provisioned however they don't join the cluster. It's suprisingly difficult to troubleshoot this because:
- nothing seems to be written to the ec2 system log
- the bottlerocket ami used doesn't seem to include the aws session manager agent which would allow me to connect to the instance for troubleshooting.

So I'm pretty much blind and unable to get anywhere. Some troubleshooting docs would be great.

**Are you currently working around this issue?**
No

**Additional context**

**Attachments**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by trondhindenes** [comment]
FYI: Diving a bit deeper into bottlerocket, there is indeed a control container which can be connected to via AWS SSM Session Manager, but from there I can't seem to get to any log files or information to help me figure out why nodes aren't joining the cluster.

**Comment by ellistarn** [comment]
Hey @trondhindenes. I totally agree that debugging bottlerocket is a pain. I'm not an expert at it myself, but they have some docs here: https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md. 

Almost all of the connection problems are due to permissions or custom launch templates. 
- Check `kubectl get configmaps -n kube-system aws-auth -oyaml` and make sure your Node Role is present there
- Check the security groups your nodes are created with `aws eks describe-cluster --name $CLUSTER_NAME --query "cluster.resourcesVpcConfig.clusterSecurityGroupId"`

I agree our docs need some work. I'll update them with the output of this discussion.

**Comment by trondhindenes** [comment]
Thanks. I'm trasferring the "getting started" to our CDK setup, and the node role EKS permission might have slipped. Double-checking. Thanks!
Still, I still feel pretty strongly that having a "cluster join log" is an absolute must...

**Comment by njtran** [comment]
As this has been open for a while and we're actively working on making our [troubleshooting doc](https://karpenter.sh/v0.8.2/troubleshooting/) better, I'm going to close this out. Feel free to cut an issue or PR to include more troubleshooting here if you run into anything.
