### ISSUE TITLE
Satisfied Labels

### ISSUE THREAD

**Issue by bdwyertech** [aws/karpenter#905]
Allow setting "satisfied" labels in the provisioner config.  Some labels are set automatically or by another process, e.g. `kubernetes.io/os`.  I have some pods which use node selectors such as this, and I cannot set these labels as these are reserved/well-known domains, so Karpenter does not know my provisioner will satisfy the condition.

![image](https://user-images.githubusercontent.com/2973273/144548628-c9aaa791-ec9e-434b-b4fc-96b79f150e1a.png)

Maybe we could have a `labels_satisfied` section?

```yaml
labels_satisified:
  kubernetes.io/os: linux
```

**Are you currently working around this issue?**
Nope.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Hmm -- is this necessary because you don't have control over these labels somehow or because you're trying to colocate on a mixed capacity cluster (non-karpenter). 

We used to support the kubernetes.io/os as a well known label, but since linux was the only supported value, we removed it. At the end of the day, we only prevent you from using well known labels -- you have full control over custom labels. If the label is well known, and useful from a scheduling perspective, we should probably just support the label.

Are there other labels other than os that you need? I'm a bit wary of supporting a new concept like "label satisfaction", and instead would lean towards just supporting OS. If you have examples of labels that would be harder for us to support as well known labels, I'd be very interested to hear what they are.

**Comment by bdwyertech** [comment]
Yeah, its because I don't have control of this specific label.  For now it's just that one, however I am curious about some others.  For example, `vpc.amazonaws.com/has-trunk-attached=true`.  Only certain instance types support Branch ENI.

With cluster-autoscaler, you would tag your ASG with labels such as this to tell the cluster-autoscaler which labels it would satisfy.  How can we achieve same with Karpenter?

**Comment by ellistarn** [comment]
`vpc.amazonaws.com/has-trunk-attached=true` is very interesting. We do have a concept of "Well Known Labels". These sound like well known labels to me, and could be used to filter instances. A couple examples:

- gpu-family
- instance-type-family
- has-nvme
- has-trunk-attached

Each of these could be modeled as "well known labels" and result in instance type filtering logic -- likely implemented here: https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/instancetype.go#L32. Of course, each of these need to be implemented, but once we have the wiring in place, if the semantic is the same, it should be very quick to introduce support.

As an alternative, we could model this using "custom labels". We could relax the validation rules on custom labels to include `.amazonaws` suffixes and allow you to specify this using `provisioner.spec.labels`. You'd be responsible for ensuring that `spec.requirements` results in the instance types that you want.

I prefer the former, since it puts less onus on the user and "just works"™️ . The latter is more in the DIY style of cluster autoscaler.

**Comment by ellistarn** [comment]
I'd love to discuss this further at https://github.com/aws/karpenter/blob/main/WORKING_GROUP.md

**Comment by geoffcline** [comment]
do we want to document that at least the label `has-trunk-attached` is unsupported in v0.5.1?

**Comment by olemarkus** [comment]
I tried using Karpenter with a few well used charts and immediately hit this issue with `kubernetes.io/os`. There is a lot of charts and other examples that use this label selector, including Node Termination Handler.

**Comment by ellistarn** [comment]
I'll see what I can do to get this re-implemented ASAP.

**Comment by bdwyertech** [comment]
I took a stab at implementing pod-eni -- Tried a few different ways but was never able to get all the tests to come together.  Will probably look at how you implement OS to get an idea for how to do this the right way.

**Comment by ellistarn** [comment]
Released in v0.5.2!
