### ISSUE TITLE
Karpenter makes wrong assumptions about CNI and kubelet max pods

### ISSUE THREAD

**Issue by olemarkus** [aws/karpenter#954]
## Expected Behavior

Karpenter either takes in max pods as a configurable constraint or does not take it into consideration when calculating the amount of pods needed.

## Actual Behavior
When small instances are provisioned, it only assigns it a handful of pods, way below what the node can actually handle.
In other cases, it creates really huge instances and assigns it hundreds of points, but the kubelet only accepts 110 (the default maxPods kubelet setting) of them.

The calculations assume that the AWS VPC CNI is used and that prefix mode is not enabled, which will be an increasingly rare configuration.

## Steps to Reproduce the Problem

Spin up 500-600 pods with cpu.request=100m on any cluster not running AWS VPC CNI.

**Comment by ellistarn** [comment]
This is on our radar and we're working on finding a solution to this as part of cohesive improvements to launch template flexibility.

**Comment by bdwyertech** [comment]
We could probably tap into the same lookup table I used for Pod ENI (might even be same value)

**Comment by ellistarn** [comment]
I'd really like to get to a world where we limit max pods by cpu/memory, and choose acceptable density/overhead values. The fact that <1.8 CNI is used widely is an inhibitor to this. I can see potentially supporting higher density by default, and including a flag that forces a more restrictive value. 

@suket22 would love your opinion on this.

**Comment by olemarkus** [comment]
In kops, most people use other CNIs. MaxPods is a per instance group configuration one can set if one wants to. Default is 110 and from my own experience one rarely has that high density. I am also not sure I ever want such high density as a significant part of capacity would be gone if the instance fails. 

Should someone use vpc cni, then same logic as Karpenter is used.

**Comment by ellistarn** [comment]
One idea to explore, use "IntOrString" to support things like `spec.density: 30`, `spec.density: vpc-cni`, `spec.density: default` (some strategy like cpu/memory)

**Comment by olemarkus** [comment]
Topology spread constraints won't do anything to avoid say 1/3 of capacity to go away if a single instance dies. 1/3 capacity going away during AZ failure may be something one gets away with, but not on a regular basis. I think a lot of cluster admins aim to have a certain amount of Nodes in the cluster and adjusts instance type thereafter. 

If karpenter intends to control max pods, it must also expose what it intends it to be so installers can configure accordingly. E.g an annotation on the Node object.

**Comment by mikesir87** [comment]
I'm using another CNI and running into this now as well. Now that we have `spec.kubeletConfiguration`, I'm thinking about creating a PR that adds a `maxPods` option there. The tricky part is the AL2 EKS-optimized AMI makes the assumption you're using the AWS CNI, unless you set `--use-max-pods=false`. So, we could allow someone to set a value of `-1` (which isn't allowed), but can be handled by the specific provider to indicate no value should be set. In the case of the AL2 AMI, we can pass along the `--use-max-pods=false` flag. Thoughts?

**Comment by olemarkus** [comment]
The important bit is the logic karpenter use internally for scheduling pods before it knows the actual Node Pod capacity.

**Comment by akestner** [comment]
Would it be possible to consolidate this and #445 since they both deal with the same problem / request?

**Comment by flaviosakakibara** [comment]
@akestner,

It would seem more logical to me, from a user perspective, to inform in the provisioner specs whereas the ENI prefix is being used in the cluster's CNI or not. Then the amount of pods could be calculated using the [MaxPodsCalculator](https://github.com/awslabs/amazon-eks-ami/blob/master/files/max-pods-calculator.sh) or any other similar method.

If we use the "max-pods" as a parameter in the provider, we'd be restricting the instance families that would match this number. This is ok if we think about reusing the created instance for other workloads but, if so, it would be a similar approach to what is obtained through Cluster Auto Scaler not? Once that all the instances from an specific ASG would have the "same" size.

In the other hand, if Karpenter's proposal is to find a "Best fit" for the current "Pending" pods, calculating the number of pods once the instance family is selected seems more accurate for me. It seems unreasonable, from the "best-fit" perspective, to search among instances that could fit a pre-defined "--max-pods 110" (considering it predefined in the provisioner) if I only have 1 pending pod due to lack of CPU.

What do you think? Have I misunderstood your suggestion? Or I could also have a wrong Idea of Karpenter's goals as well...
