### ISSUE TITLE
podAffinity

### ISSUE THREAD

**Issue by olemarkus** [aws/karpenter#985]
**Tell us about your request**
What do you want us to build?

I know you'll love this: Support `podAffinity`

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
This is a sibling issue to #942 , but specifically on `podAffinity`.

Cilium's hubble has component called hubble-relay that needs to run on the same node as a cilium agent.
The cilium install manifests has this podAffinity as non-optional: https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/hubble-relay/deployment.yaml#L34-L43

This is a fairly essential component to those using Cilium.

On many clusters, one can assume cilium agent on all nodes, but there are clusters with Fargate nodes and Windows nodes using Cilium, where the agent wouldn't run.

**Are you currently working around this issue?**

In our case, we can patch out that podAffinity.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tmokmss** [comment]
+1 to podAffinity support

We're investigating if we can use Karpenter with Agones, and found that Agones use podAffinity for pod scheduling to pack as much as possible into the smallest set of nodes. [doc](https://agones.dev/site/docs/advanced/scheduling-and-autoscaling/#pod-scheduling-strategy)
Because Karpenter currently ignores pods with podAffinity, we cannot use Karpenter to provision nodes for Agones pods.

**Comment by ellistarn** [comment]
What if the pods aren't created at the same time? If Karpenter only sees the first pod, it will launch a node for it. If the next pod c omes in a minute later, it's too late for that pod to be included in the scheduling algorithm. This doesn't exist for anti-affinity because scheduling apart achieves the same objective.

I'd love to make progress on podaffinity, but I don't have a viable path forward. How are you envisioning it?

**Comment by tmokmss** [comment]
Hi thanks for the suggestion. As the doc says 

> The default Kubernetes scheduler doesn’t do a perfect job of packing, but it’s a good enough job for what we need - at least at this stage.

Agones itself admits it isn't perfect, but they seem to know it works well at most cases.

**Comment by ellistarn** [comment]
Reading through agones, preferred pod affinity would be doable.

**Comment by tmokmss** [comment]
Sounds great! Dedicated game servers tend to need much rapid auto scaling, so Karpenter with Agones would be fantastic I believe 👍

**Comment by ellistarn** [comment]
Further, as I study the podaffintiy page, I think it would also be doable to implement zonal podaffinity (e.g. schedule all pods to a specific zone).

**Comment by tzneal** [comment]
If you've got a fairly recent version of Karpenter already running, you can drop in this snapshot controller image to test out pod affinity & pod anti-affinity.  This is just a snapshot, not meant for production, etc.:

```
kubectl set image deployment/karpenter -n karpenter controller=public.ecr.aws/z4v8y7u8/controller:08ac9ec303aabe2da56edb0ee0e235a60a287206
```
